classdef testAutoDiffPropagators < matlab.unittest.TestCase
    %% DESCRIPTION
    % Numerical behavioral tests for the automatic-differentiation propagation
    % interfaces. These tests run without adding CasADi to the MATLAB path and
    % verify parity with the canonical numerical kernels and MATLAB ode45.
    % -------------------------------------------------------------------------------------------------------------
    %% CHANGELOG
    % 28-07-2026  Pietro Califano, Codex     First numerical AutoDiff propagation regressions.
    % -------------------------------------------------------------------------------------------------------------

    methods (Test)
        function testAutoDiffStepsMatchCanonicalNumericalSteps(self)
            % AutoDiff-capable kernels must preserve the numerical RK4/RK8
            % formulas and exact advanced timestamp.
            dCurrentTime = 0.35;
            dxCurrentState = [0.4; -0.15];
            dStepSize = 0.17;
            strDynParams = struct('dDamping', 0.2, 'dForcing', 0.08);
            strModelConfigFlags = struct();

            [dxExpectedRK4State, dExpectedRK4Time] = PropagateRK4Step( ...
                @ParameterizedNonlinearRhs_, dCurrentTime, ...
                dxCurrentState, dStepSize, strDynParams, ...
                strModelConfigFlags);
            [dxExpectedRK8State, dExpectedRK8Time] = PropagateRK8Step( ...
                @ParameterizedNonlinearRhs_, dCurrentTime, ...
                dxCurrentState, dStepSize, strDynParams, ...
                strModelConfigFlags);

            [dxRK4State, dRK4Time] = PropagateRK4StepAutoDiff( ...
                @ParameterizedNonlinearRhs_, dCurrentTime, ...
                dxCurrentState, dStepSize, strDynParams, ...
                strModelConfigFlags);
            [dxRK8State, dRK8Time] = PropagateRK8StepAutoDiff( ...
                @ParameterizedNonlinearRhs_, dCurrentTime, ...
                dxCurrentState, dStepSize, strDynParams, ...
                strModelConfigFlags);

            self.verifyEqual(dxRK4State, dxExpectedRK4State, ...
                'AbsTol', 10.0 * eps);
            self.verifyEqual(dxRK8State, dxExpectedRK8State, ...
                'AbsTol', 10.0 * eps);
            self.verifyEqual([dRK4Time, dRK8Time], ...
                [dExpectedRK4Time, dExpectedRK8Time], ...
                'AbsTol', 10.0 * eps);
        end

        function testAdaptiveAutoDiffMatchesOde45InBothDirections(self)
            % The double path must retain adaptive accuracy, monotonic grids,
            % and exact endpoints independently of CasADi availability.
            dxInitialState = [0.4; -0.15];
            strDynParams = struct('dDamping', 0.2, 'dForcing', 0.08);
            strModelConfigFlags = struct();
            strOdeOptions = odeset( ...
                'RelTol', 1.0e-12, 'AbsTol', 1.0e-14);

            [dxForwardHistory, dForwardGrid, strForwardStatistics] = ...
                PropagateAdaptiveStepAutoDiff( ...
                @ParameterizedNonlinearRhs_, [0.0, 2.0], ...
                dxInitialState, 0.4, strDynParams, ...
                strModelConfigFlags, ...
                dRelativeTolerance=1.0e-10, ...
                dAbsoluteTolerance=1.0e-12);
            [dForwardReferenceGrid, dxForwardReference] = ode45( ...
                @(dTime, dxState) ParameterizedNonlinearRhs_( ...
                dTime, dxState, strDynParams, strModelConfigFlags), ...
                dForwardGrid, dxInitialState, strOdeOptions);

            self.verifyEqual(dForwardReferenceGrid, dForwardGrid);
            self.verifyEqual(dForwardGrid([1, end]), [0.0; 2.0]);
            self.verifyTrue(all(diff(dForwardGrid) > 0.0));
            VerifyScaleAwareParity_(self, dxForwardHistory, ...
                dxForwardReference, 5.0e-11, 5.0e-11);
            self.verifyGreaterThan( ...
                strForwardStatistics.ui32AcceptedSteps, uint32(0));

            dxBackwardInitialState = dxForwardReference(end, :).';
            [dxBackwardHistory, dBackwardGrid] = ...
                PropagateAdaptiveStepAutoDiff( ...
                @ParameterizedNonlinearRhs_, [2.0, 0.0], ...
                dxBackwardInitialState, 0.4, strDynParams, ...
                strModelConfigFlags, ...
                dRelativeTolerance=1.0e-10, ...
                dAbsoluteTolerance=1.0e-12);
            [dBackwardReferenceGrid, dxBackwardReference] = ode45( ...
                @(dTime, dxState) ParameterizedNonlinearRhs_( ...
                dTime, dxState, strDynParams, strModelConfigFlags), ...
                dBackwardGrid, dxBackwardInitialState, strOdeOptions);

            self.verifyEqual(dBackwardReferenceGrid, dBackwardGrid);
            self.verifyEqual(dBackwardGrid([1, end]), [2.0; 0.0]);
            self.verifyTrue(all(diff(dBackwardGrid) < 0.0));
            VerifyScaleAwareParity_(self, dxBackwardHistory, ...
                dxBackwardReference, 5.0e-11, 5.0e-11);
        end

        function testAdaptiveAutoDiffZeroDurationSkipsRhs(self)
            % A zero-duration interval must preserve row-oriented state output
            % and must not evaluate the supplied dynamics.
            [dxStateHistory, dTimeGrid, strStatistics] = ...
                PropagateAdaptiveStepAutoDiff( ...
                @ErrorRhs_, [5.0, 5.0], [1.0; 2.0], 0.2, ...
                struct(), struct());

            self.verifyEqual(dxStateHistory, [1.0, 2.0]);
            self.verifyEqual(dTimeGrid, 5.0);
            self.verifyEqual( ...
                strStatistics.ui32AcceptedSteps, uint32(0));
            self.verifyEqual( ...
                strStatistics.ui32FunctionEvaluations, uint32(0));
        end

        function testAutoDiffInterfacesForwardExplicitRhsInputs(self)
            % Runtime dynamics data and model flags must reach every restored
            % AutoDiff integration boundary without a repeating argument pack.
            strDynParams = struct('dConstantDerivative', 2.0);
            strModelConfigFlags = struct('bNegateDerivative', false);
            cellStepFunctions = {@PropagateRK4StepAutoDiff, ...
                @PropagateRK8StepAutoDiff};

            for ui32StepIndex = uint32(1):uint32(numel(cellStepFunctions))
                [dxAdvancedState, dAdvancedTime] = ...
                    cellStepFunctions{double(ui32StepIndex)}( ...
                    @ExplicitPayloadRhs_, 0.0, 1.0, 0.2, ...
                    strDynParams, strModelConfigFlags);

                self.verifyEqual(dxAdvancedState, 1.4, ...
                    'AbsTol', 10.0 * eps);
                self.verifyEqual(dAdvancedTime, 0.2, ...
                    'AbsTol', 10.0 * eps);
            end

            [dxStateHistory, dTimeGrid] = ...
                PropagateAdaptiveStepAutoDiff( ...
                @ExplicitPayloadRhs_, [0.0, 0.5], 1.0, 0.3, ...
                strDynParams, strModelConfigFlags);

            self.verifyEqual(dxStateHistory(end), 2.0, ...
                'AbsTol', 20.0 * eps);
            self.verifyEqual(dTimeGrid([1, end]), [0.0; 0.5], ...
                'AbsTol', 10.0 * eps);
        end
    end
end

function dxDerivative = ParameterizedNonlinearRhs_( ...
    dTime, dxState, strDynParams, ~)
% Return a parameterized nonlinear oscillator for independent ODE parity.
dxDerivative = [dxState(2); ...
    -sin(dxState(1)) - strDynParams.dDamping * dxState(2) + ...
    strDynParams.dForcing * cos(0.7 * dTime)];
end

function dxDerivative = ExplicitPayloadRhs_( ...
    dTime, dxState, strDynParams, strModelConfigFlags)
% Require both standard RHS structs to produce the expected derivative.
dSign = 1.0 - 2.0 * double(strModelConfigFlags.bNegateDerivative);
dxDerivative = dSign * strDynParams.dConstantDerivative * ...
    ones(size(dxState)) + 0.0 * dTime;
end

function dxDerivative = ErrorRhs_(~, dxState, ~, ~)
% Fail if a zero-duration provider evaluates the RHS.
dxDerivative = dxState;
error('testAutoDiffPropagators:UnexpectedRhsEvaluation', ...
    'The RHS must not be evaluated for a zero-duration interval.');
end

function VerifyScaleAwareParity_( ...
    self, dxActualHistory, dxReferenceHistory, ...
    dAbsoluteTolerance, dRelativeTolerance)
% Compare full histories through an element-wise mixed tolerance.
self.verifySize(dxActualHistory, size(dxReferenceHistory));
dAllowedDifference = dAbsoluteTolerance + ...
    dRelativeTolerance * abs(dxReferenceHistory);
dNormalizedDifference = abs(dxActualHistory - dxReferenceHistory) ./ ...
    dAllowedDifference;
self.verifyLessThanOrEqual(max(dNormalizedDifference, [], 'all'), 1.0);
end
