classdef testAutoDiffPropagatorsCasadi < matlab.unittest.TestCase
    %% DESCRIPTION
    % CasADi 3.6.7 regressions for symbolic SimulationGears propagation.
    % The suite loads the optional local CasADi distribution explicitly and
    % verifies symbolic flow construction, Jacobians, adaptive parity, and
    % exact output timestamps.
    % -------------------------------------------------------------------------------------------------------------
    %% CHANGELOG
    % 28-07-2026  Pietro Califano, Codex     First CasADi AutoDiff propagation regressions.
    % -------------------------------------------------------------------------------------------------------------

    methods (TestClassSetup)
        function loadCasadi367(self)
            % Load only the explicitly approved optional CasADi distribution.
            charTestFile = mfilename('fullpath');
            charRepositoryRoot = fileparts(fileparts(fileparts( ...
                fileparts(fileparts(charTestFile)))));
            charCasadiRoot = fullfile(fileparts(charRepositoryRoot), ...
                'casadi', 'matlab', 'casadi_matlab_3.6.7');
            self.assumeTrue(isfolder(charCasadiRoot), ...
                'The installed CasADi 3.6.7 MATLAB package was not found.');
            self.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                charCasadiRoot));
            self.assertEqual(string(casadi.CasadiMeta.version()), "3.6.7");
        end
    end

    methods (Test)
        function testSXStepsBuildDifferentiableRK4AndRK8Flows(self)
            % Both explicit step kernels must accept SX state graphs and
            % produce numerical values matching the canonical double kernels.
            objInitialState = casadi.SX.sym('objInitialState', 2, 1);
            dCurrentTime = 0.35;
            dStepSize = 0.17;
            strDynParams = struct('dDamping', 0.2, 'dForcing', 0.08);
            strModelConfigFlags = struct();

            [objRK4State, dRK4Time] = PropagateRK4StepAutoDiff( ...
                @ParameterizedNonlinearRhs_, dCurrentTime, ...
                objInitialState, dStepSize, strDynParams, ...
                strModelConfigFlags);
            [objRK8State, dRK8Time] = PropagateRK8StepAutoDiff( ...
                @ParameterizedNonlinearRhs_, dCurrentTime, ...
                objInitialState, dStepSize, strDynParams, ...
                strModelConfigFlags);

            self.verifyClass(objRK4State, 'casadi.SX');
            self.verifyClass(objRK8State, 'casadi.SX');
            self.verifyEqual([dRK4Time, dRK8Time], [0.52, 0.52], ...
                'AbsTol', 10.0 * eps);

            objRK4Function = casadi.Function( ...
                'TestRK4AutoDiffFlow', {objInitialState}, {objRK4State});
            objRK8Function = casadi.Function( ...
                'TestRK8AutoDiffFlow', {objInitialState}, {objRK8State});
            dxInitialState = [0.4; -0.15];
            dxRK4State = full(objRK4Function(dxInitialState));
            dxRK8State = full(objRK8Function(dxInitialState));

            dxExpectedRK4State = PropagateRK4Step( ...
                @ParameterizedNonlinearRhs_, dCurrentTime, ...
                dxInitialState, dStepSize, strDynParams, ...
                strModelConfigFlags);
            dxExpectedRK8State = PropagateRK8Step( ...
                @ParameterizedNonlinearRhs_, dCurrentTime, ...
                dxInitialState, dStepSize, strDynParams, ...
                strModelConfigFlags);
            self.verifyEqual(dxRK4State, dxExpectedRK4State, ...
                'AbsTol', 10.0 * eps);
            self.verifyEqual(dxRK8State, dxExpectedRK8State, ...
                'AbsTol', 10.0 * eps);

            % An independently differenced flow Jacobian verifies that the
            % returned RK4 expression remains differentiable through CasADi.
            objRK4Jacobian = objRK4State.jacobian(objInitialState);
            objRK4JacobianFunction = casadi.Function( ...
                'TestRK4AutoDiffJacobian', {objInitialState}, ...
                {objRK4Jacobian});
            dAutoDiffJacobian = full( ...
                objRK4JacobianFunction(dxInitialState));
            dFiniteDifferenceJacobian = DifferentiateFlow_( ...
                @(dxState) full(objRK4Function(dxState)), dxInitialState);
            self.verifyEqual(dAutoDiffJacobian, ...
                dFiniteDifferenceJacobian, 'AbsTol', 2.0e-7);

            self.verifyError(@() PropagateAdaptiveStepAutoDiff( ...
                @ParameterizedNonlinearRhs_, [0.0, 1.0], ...
                objInitialState, 0.2, strDynParams, ...
                strModelConfigFlags), ...
                'PropagateAdaptiveStepAutoDiff:SXAdaptiveUnsupported');
        end

        function testMXStepsSupportSignedBackwardAdvance(self)
            % MX fixed-step graphs must retain both RK formulas when the
            % signed step advances backward in physical time.
            objInitialState = casadi.MX.sym('objInitialState', 2, 1);
            dxInitialState = [0.4; -0.15];
            dCurrentTime = 0.35;
            dStepSize = -0.17;
            strDynParams = struct('dDamping', 0.2, 'dForcing', 0.08);

            [objRK4State, dRK4Time] = PropagateRK4StepAutoDiff( ...
                @ParameterizedNonlinearRhs_, dCurrentTime, ...
                objInitialState, dStepSize, strDynParams, struct());
            [objRK8State, dRK8Time] = PropagateRK8StepAutoDiff( ...
                @ParameterizedNonlinearRhs_, dCurrentTime, ...
                objInitialState, dStepSize, strDynParams, struct());
            objStepFunction = casadi.Function( ...
                'TestMXAutoDiffSteps', {objInitialState}, ...
                {objRK4State, objRK8State});
            [objRK4Value, objRK8Value] = ...
                objStepFunction(dxInitialState);

            dxExpectedRK4State = PropagateRK4Step( ...
                @ParameterizedNonlinearRhs_, dCurrentTime, ...
                dxInitialState, dStepSize, strDynParams, struct());
            dxExpectedRK8State = PropagateRK8Step( ...
                @ParameterizedNonlinearRhs_, dCurrentTime, ...
                dxInitialState, dStepSize, strDynParams, struct());

            self.verifyClass(objRK4State, 'casadi.MX');
            self.verifyClass(objRK8State, 'casadi.MX');
            self.verifyEqual(full(objRK4Value), ...
                dxExpectedRK4State, 'AbsTol', 10.0 * eps);
            self.verifyEqual(full(objRK8Value), ...
                dxExpectedRK8State, 'AbsTol', 10.0 * eps);
            self.verifyEqual([dRK4Time, dRK8Time], [0.18, 0.18], ...
                'AbsTol', 10.0 * eps);
        end

        function testMXAdaptiveFlowMatchesOde45AndExactGrid(self)
            % CasADi's adaptive backend must expose a differentiable MX
            % trajectory on deterministic output timestamps.
            objInitialState = casadi.MX.sym('objInitialState', 2, 1);
            dxInitialState = [0.4; -0.15];
            strDynParams = struct('dDamping', 0.2, 'dForcing', 0.08);
            strModelConfigFlags = struct();

            [objStateHistory, dTimeGrid, strStatistics] = ...
                PropagateAdaptiveStepAutoDiff( ...
                @ParameterizedNonlinearRhs_, [0.0, 1.3], ...
                objInitialState, 0.4, strDynParams, ...
                strModelConfigFlags, ...
                dRelativeTolerance=1.0e-10, ...
                dAbsoluteTolerance=1.0e-12);

            self.verifyClass(objStateHistory, 'casadi.MX');
            self.verifyEqual(dTimeGrid, [0.0; 0.4; 0.8; 1.2; 1.3], ...
                'AbsTol', 10.0 * eps);
            self.verifyEmpty(strStatistics);

            objFlowFunction = casadi.Function( ...
                'TestAdaptiveAutoDiffFlow', {objInitialState}, ...
                {objStateHistory});
            dxStateHistory = full(objFlowFunction(dxInitialState));
            strOdeOptions = odeset( ...
                'RelTol', 1.0e-12, 'AbsTol', 1.0e-14);
            [dReferenceGrid, dxReferenceHistory] = ode45( ...
                @(dTime, dxState) ParameterizedNonlinearRhs_( ...
                dTime, dxState, strDynParams, strModelConfigFlags), ...
                dTimeGrid, dxInitialState, strOdeOptions);

            self.verifyEqual(dReferenceGrid, dTimeGrid);
            VerifyScaleAwareParity_(self, dxStateHistory, ...
                dxReferenceHistory, 2.0e-9, 2.0e-9);

            objFinalState = objStateHistory(end, :).';
            objFinalJacobian = objFinalState.jacobian(objInitialState);
            objFinalJacobianFunction = casadi.Function( ...
                'TestAdaptiveAutoDiffJacobian', {objInitialState}, ...
                {objFinalJacobian});
            dAutoDiffJacobian = full( ...
                objFinalJacobianFunction(dxInitialState));
            dFiniteDifferenceJacobian = DifferentiateFlow_( ...
                @(dxState) ExtractFinalState_( ...
                objFlowFunction, dxState), dxInitialState);
            self.verifyEqual(dAutoDiffJacobian, ...
                dFiniteDifferenceJacobian, 'AbsTol', 2.0e-5);
        end

        function testMXAdaptiveFlowSupportsBackwardAndZeroDuration(self)
            % Symbolic output grids must remain exact for backward and
            % zero-duration intervals without evaluating unresolved branches.
            objInitialState = casadi.MX.sym('objInitialState', 2, 1);
            strDynParams = struct('dDamping', 0.2, 'dForcing', 0.08);
            strModelConfigFlags = struct();

            [objBackwardHistory, dBackwardGrid] = ...
                PropagateAdaptiveStepAutoDiff( ...
                @ParameterizedNonlinearRhs_, [1.0, 0.0], ...
                objInitialState, 0.3, strDynParams, ...
                strModelConfigFlags, ...
                dRelativeTolerance=1.0e-10, ...
                dAbsoluteTolerance=1.0e-12);
            self.verifyClass(objBackwardHistory, 'casadi.MX');
            self.verifyEqual(dBackwardGrid, ...
                [1.0; 0.7; 0.4; 0.1; 0.0], ...
                'AbsTol', 32.0 * eps);
            self.verifyTrue(all(diff(dBackwardGrid) < 0.0));

            objBackwardFunction = casadi.Function( ...
                'TestBackwardAutoDiffFlow', {objInitialState}, ...
                {objBackwardHistory});
            dxBackwardInitialState = [0.35; -0.1];
            dxBackwardHistory = full( ...
                objBackwardFunction(dxBackwardInitialState));
            strOdeOptions = odeset( ...
                'RelTol', 1.0e-12, 'AbsTol', 1.0e-14);
            [dBackwardReferenceGrid, dxBackwardReference] = ode45( ...
                @(dTime, dxState) ParameterizedNonlinearRhs_( ...
                dTime, dxState, strDynParams, strModelConfigFlags), ...
                dBackwardGrid, dxBackwardInitialState, strOdeOptions);
            self.verifyEqual(dBackwardReferenceGrid, dBackwardGrid);
            VerifyScaleAwareParity_(self, dxBackwardHistory, ...
                dxBackwardReference, 2.0e-9, 2.0e-9);

            [objZeroHistory, dZeroGrid, strZeroStatistics] = ...
                PropagateAdaptiveStepAutoDiff( ...
                @ErrorRhs_, [5.0, 5.0], objInitialState, 0.2, ...
                struct(), struct());
            self.verifyClass(objZeroHistory, 'casadi.MX');
            self.verifySize(objZeroHistory, [1, 2]);
            self.verifyEqual(dZeroGrid, 5.0);
            self.verifyEmpty(strZeroStatistics);
        end

        function testMXAdaptiveMaximumStepControlsOutputGrid(self)
            % A configured maximum below the initial step must bound the
            % deterministic output spacing while retaining a valid MX flow.
            objInitialState = casadi.MX.sym('objInitialState', 2, 1);
            strDynParams = struct('dDamping', 0.2, 'dForcing', 0.08);

            [objStateHistory, dTimeGrid] = ...
                PropagateAdaptiveStepAutoDiff( ...
                @ParameterizedNonlinearRhs_, [0.0, 0.55], ...
                objInitialState, 0.4, strDynParams, struct(), ...
                dMaximumStep=0.2, ...
                dRelativeTolerance=1.0e-10, ...
                dAbsoluteTolerance=1.0e-12);

            self.verifyEqual(dTimeGrid, [0.0; 0.2; 0.4; 0.55], ...
                'AbsTol', 10.0 * eps);
            objFlowFunction = casadi.Function( ...
                'TestMaximumStepAutoDiffFlow', {objInitialState}, ...
                {objStateHistory});
            dxStateHistory = full(objFlowFunction([0.4; -0.15]));
            self.verifySize(dxStateHistory, [4, 2]);
        end
    end
end

function dxDerivative = ParameterizedNonlinearRhs_( ...
    dTime, dxState, strDynParams, ~)
% Return dynamics expressed with operators shared by doubles and CasADi.
dxDerivative = [dxState(2); ...
    -sin(dxState(1)) - strDynParams.dDamping * dxState(2) + ...
    strDynParams.dForcing * cos(0.7 * dTime)];
end

function dxDerivative = ErrorRhs_(~, dxState, ~, ~)
% Fail if zero-duration symbolic propagation evaluates the RHS.
dxDerivative = dxState;
error('testAutoDiffPropagatorsCasadi:UnexpectedRhsEvaluation', ...
    'The RHS must not be evaluated for a zero-duration interval.');
end

function dJacobian = DifferentiateFlow_(fcnFlow, dxInitialState)
% Form an independent central-difference Jacobian of a numerical flow map.
dPerturbation = 1.0e-6;
dStateSize = numel(dxInitialState);
dReferenceOutput = fcnFlow(dxInitialState);
dJacobian = zeros(numel(dReferenceOutput), dStateSize);

for ui32StateIndex = uint32(1):uint32(dStateSize)
    dxPositiveState = dxInitialState;
    dxNegativeState = dxInitialState;
    dxPositiveState(double(ui32StateIndex)) = ...
        dxPositiveState(double(ui32StateIndex)) + dPerturbation;
    dxNegativeState(double(ui32StateIndex)) = ...
        dxNegativeState(double(ui32StateIndex)) - dPerturbation;
    dJacobian(:, double(ui32StateIndex)) = ...
        (fcnFlow(dxPositiveState) - fcnFlow(dxNegativeState)) / ...
        (2.0 * dPerturbation);
end
end

function dxFinalState = ExtractFinalState_(objFlowFunction, dxInitialState)
% Evaluate a CasADi trajectory function and return its final state column.
dxStateHistory = full(objFlowFunction(dxInitialState));
dxFinalState = dxStateHistory(end, :).';
end

function VerifyScaleAwareParity_( ...
    self, dxActualHistory, dxReferenceHistory, ...
    dAbsoluteTolerance, dRelativeTolerance)
% Compare full histories through an element-wise mixed tolerance.
self.verifySize(dxActualHistory, size(dxReferenceHistory));
dAllowedDifference = dAbsoluteTolerance + ...
    dRelativeTolerance * abs(dxReferenceHistory);
dNormalizedDifference = abs(dxActualHistory - dxReferenceHistory) ./ ...
    dAllowedDifference;
self.verifyLessThanOrEqual(max(dNormalizedDifference, [], 'all'), 1.0);
end
