classdef testNumericalPropagators < matlab.unittest.TestCase
    %% DESCRIPTION
    % Behavioral tests for the shared SimulationGears numerical propagators.
    % The suite verifies trajectory layout, integration direction, convergence,
    % adaptive error control, MATLAB ODE parity, public-input diagnostics, and
    % generated-code specialization of the fixed-step scheme.
    % -------------------------------------------------------------------------------------------------------------
    %% CHANGELOG
    % 27-07-2026  Pietro Califano, Codex     First behavioral regression suite.
    % -------------------------------------------------------------------------------------------------------------

    methods (Test)
        function testRK2AndRK8StepsAdvanceState(self)
            % Both public step variants must preserve column-state layout and
            % return the advanced timestamp without trajectory allocation.
            dStepSize = 0.1;
            dExpectedHeunState = 1.0 + dStepSize + dStepSize^2 / 2.0;

            [dxHeunState, dHeunTime] = PropagateRK2HeunStep( ...
                @GrowthRhs_, 3.0, 1.0, dStepSize, struct(), struct());
            [dxRK8State, dRK8Time] = PropagateRK8Step( ...
                @GrowthRhs_, 3.0, 1.0, dStepSize, struct(), struct());

            self.verifyEqual(dxHeunState, dExpectedHeunState, ...
                'AbsTol', 10.0 * eps);
            self.verifyEqual(dxRK8State, exp(dStepSize), 'AbsTol', 1.0e-12);
            self.verifyEqual([dHeunTime, dRK8Time], [3.1, 3.1], ...
                'AbsTol', 10.0 * eps);
        end

        function testRK4StepAdvancesTimeAndState(self)
            % One public step must return only the advanced state and time.
            dStepSize = 0.1;
            dExpectedState = 1.0 + dStepSize + dStepSize^2 / 2.0 + ...
                dStepSize^3 / 6.0 + dStepSize^4 / 24.0;

            [dxAdvancedState, dAdvancedTime] = PropagateRK4Step( ...
                @GrowthRhs_, 2.0, 1.0, dStepSize, struct(), struct());

            self.verifyEqual(dxAdvancedState, dExpectedState, ...
                'AbsTol', 10.0 * eps);
            self.verifyEqual(dAdvancedTime, 2.1, 'AbsTol', 10.0 * eps);
        end

        function testExplicitRhsInputsReachEveryNumericalStage(self)
            % Dropping either standard RHS struct at any stage must change or
            % fail the observable propagation result.
            strDynParams = struct('dConstantDerivative', 2.0);
            strModelConfigFlags = struct('bNegateDerivative', false);
            cellStepFunctions = {@PropagateRK2HeunStep, ...
                @PropagateRK4Step, @PropagateRK8Step};

            for ui32StepIndex = uint32(1):uint32(numel(cellStepFunctions))
                [dxAdvancedState, dAdvancedTime] = ...
                    cellStepFunctions{double(ui32StepIndex)}( ...
                    @ExplicitPayloadRhs_, 0.0, 1.0, 0.2, ...
                    strDynParams, strModelConfigFlags);

                self.verifyEqual(dxAdvancedState, 1.4, ...
                    'AbsTol', 10.0 * eps);
                self.verifyEqual(dAdvancedTime, 0.2, ...
                    'AbsTol', 10.0 * eps);
            end

            [dxFixedHistory, dFixedGrid] = PropagateFixedStep( ...
                @ExplicitPayloadRhs_, [0.0, 0.5], 1.0, 0.3, ...
                strDynParams, strModelConfigFlags, ...
                EnumFixedStepScheme.RK4);
            [dxAdaptiveHistory, dAdaptiveGrid] = PropagateAdaptiveStep( ...
                @ExplicitPayloadRhs_, [0.0, 0.5], 1.0, 0.3, ...
                strDynParams, strModelConfigFlags);

            self.verifyEqual(dxFixedHistory(end), 2.0, ...
                'AbsTol', 20.0 * eps);
            self.verifyEqual(dxAdaptiveHistory(end), 2.0, ...
                'AbsTol', 20.0 * eps);
            self.verifyEqual(dFixedGrid, [0.0; 0.3; 0.5], ...
                'AbsTol', 10.0 * eps);
            self.verifyEqual(dAdaptiveGrid([1, end]), [0.0; 0.5], ...
                'AbsTol', 10.0 * eps);
        end

        function testRK4ForwardGridAndDimension(self)
            % A shortened final step must reach the exact endpoint without
            % changing the state-history row contract.
            dxInitialState = [1.0; 0.0];

            [dxStateHistory, dTimeGrid, strStatistics] = PropagateFixedStep( ...
                @OscillatorRhs_, [0.0, 1.0], dxInitialState, 0.3, ...
                struct(), struct(), EnumFixedStepScheme.RK4);

            self.verifyEqual(dTimeGrid, [0.0; 0.3; 0.6; 0.9; 1.0], ...
                'AbsTol', 10.0 * eps);
            self.verifySize(dxStateHistory, [5, 2]);
            self.verifyEqual(dxStateHistory(1, :).', dxInitialState);
            self.verifyEqual(strStatistics.ui32AcceptedSteps, uint32(4));
            self.verifyEqual(strStatistics.ui32RejectedSteps, uint32(0));
            self.verifyEqual(strStatistics.ui32FunctionEvaluations, uint32(16));
        end

        function testRK2AndRK8IntervalContracts(self)
            % Fixed-step scheme variants must share the same endpoint,
            % history orientation, and evaluation-count contracts.
            dxInitialState = [1.0; 0.0];

            [dxHeunHistory, dHeunGrid, strHeunStatistics] = ...
                PropagateFixedStep(@OscillatorRhs_, [0.0, 1.0], ...
                dxInitialState, 0.4, struct(), struct(), ...
                EnumFixedStepScheme.RK2Heun);
            [dxRK8History, dRK8Grid, strRK8Statistics] = ...
                PropagateFixedStep(@OscillatorRhs_, [0.0, 1.0], ...
                dxInitialState, 0.4, struct(), struct(), ...
                EnumFixedStepScheme.RK8);

            dExpectedGrid = [0.0; 0.4; 0.8; 1.0];
            self.verifyEqual(dHeunGrid, dExpectedGrid, ...
                'AbsTol', 10.0 * eps);
            self.verifyEqual(dRK8Grid, dExpectedGrid, ...
                'AbsTol', 10.0 * eps);
            self.verifySize(dxHeunHistory, [4, 2]);
            self.verifySize(dxRK8History, [4, 2]);
            self.verifyEqual(strHeunStatistics.ui32FunctionEvaluations, ...
                uint32(6));
            self.verifyEqual(strRK8Statistics.ui32FunctionEvaluations, ...
                uint32(39));
        end

        function testFixedPropagatorsConvergeAtExpectedOrders(self)
            % Step halving must reduce global error consistently with each
            % method's advertised order.
            dExactFinalState = exp(1.0);

            dxHeunCoarse = PropagateFixedStep( ...
                @GrowthRhs_, [0.0, 1.0], 1.0, 0.25, ...
                struct(), struct(), EnumFixedStepScheme.RK2Heun);
            dxHeunFine = PropagateFixedStep( ...
                @GrowthRhs_, [0.0, 1.0], 1.0, 0.125, ...
                struct(), struct(), EnumFixedStepScheme.RK2Heun);
            dxRK4Coarse = PropagateFixedStep( ...
                @GrowthRhs_, [0.0, 1.0], 1.0, 0.25, ...
                struct(), struct(), EnumFixedStepScheme.RK4);
            dxRK4Fine = PropagateFixedStep( ...
                @GrowthRhs_, [0.0, 1.0], 1.0, 0.125, ...
                struct(), struct(), EnumFixedStepScheme.RK4);
            dxRK8Coarse = PropagateFixedStep( ...
                @GrowthRhs_, [0.0, 1.0], 1.0, 0.5, ...
                struct(), struct(), EnumFixedStepScheme.RK8);
            dxRK8Fine = PropagateFixedStep( ...
                @GrowthRhs_, [0.0, 1.0], 1.0, 0.25, ...
                struct(), struct(), EnumFixedStepScheme.RK8);

            dHeunErrorRatio = abs(dxHeunCoarse(end) - dExactFinalState) / ...
                abs(dxHeunFine(end) - dExactFinalState);
            dRK4ErrorRatio = abs(dxRK4Coarse(end) - dExactFinalState) / ...
                abs(dxRK4Fine(end) - dExactFinalState);
            dRK8ErrorRatio = abs(dxRK8Coarse(end) - dExactFinalState) / ...
                abs(dxRK8Fine(end) - dExactFinalState);

            self.verifyGreaterThan(dHeunErrorRatio, 3.5);
            self.verifyGreaterThan(dRK4ErrorRatio, 12.0);
            self.verifyGreaterThan(dRK8ErrorRatio, 150.0);
        end

        function testRK8ConvergesForGenericFirstOrderDynamics(self)
            % Eighth-order convergence must hold for nonlinear autonomous
            % and explicitly time-dependent dynamics, not only linear growth.
            dCoarseStep = 0.5;
            dFineStep = 0.25;

            dxNonlinearCoarse = PropagateFixedStep( ...
                @QuadraticGrowthRhs_, [0.0, 1.0], 0.25, dCoarseStep, ...
                struct(), struct(), EnumFixedStepScheme.RK8);
            dxNonlinearFine = PropagateFixedStep( ...
                @QuadraticGrowthRhs_, [0.0, 1.0], 0.25, dFineStep, ...
                struct(), struct(), EnumFixedStepScheme.RK8);
            dxTimeVaryingCoarse = PropagateFixedStep( ...
                @TimeVaryingGrowthRhs_, [0.0, 1.0], 1.0, dCoarseStep, ...
                struct(), struct(), EnumFixedStepScheme.RK8);
            dxTimeVaryingFine = PropagateFixedStep( ...
                @TimeVaryingGrowthRhs_, [0.0, 1.0], 1.0, dFineStep, ...
                struct(), struct(), EnumFixedStepScheme.RK8);

            dExactNonlinearState = 1.0 / 3.0;
            dExactTimeVaryingState = exp(0.5);
            dNonlinearErrorRatio = ...
                abs(dxNonlinearCoarse(end) - dExactNonlinearState) / ...
                abs(dxNonlinearFine(end) - dExactNonlinearState);
            dTimeVaryingErrorRatio = ...
                abs(dxTimeVaryingCoarse(end) - dExactTimeVaryingState) / ...
                abs(dxTimeVaryingFine(end) - dExactTimeVaryingState);

            self.verifyGreaterThan(dNonlinearErrorRatio, 180.0);
            self.verifyGreaterThan(dTimeVaryingErrorRatio, 180.0);
        end

        function testRKF45HonorsToleranceAndCountsRejectedSteps(self)
            % Tightening the tolerance must improve the final state while a
            % deliberately large first step exercises rejection accounting.
            [dxLooseHistory, dLooseGrid] = ...
                PropagateAdaptiveStep(@GrowthRhs_, [0.0, 2.0], 1.0, 2.0, ...
                struct(), struct(), ...
                dRelativeTolerance=1.0e-3, ...
                dAbsoluteTolerance=1.0e-6);
            [dxTightHistory, dTightGrid, strTightStatistics] = ...
                PropagateAdaptiveStep(@GrowthRhs_, [0.0, 2.0], 1.0, 2.0, ...
                struct(), struct(), ...
                dRelativeTolerance=1.0e-10, ...
                dAbsoluteTolerance=1.0e-12);

            dExactFinalState = exp(2.0);
            dLooseError = abs(dxLooseHistory(end) - dExactFinalState);
            dTightError = abs(dxTightHistory(end) - dExactFinalState);

            self.verifyEqual(dLooseGrid(end), 2.0);
            self.verifyEqual(dTightGrid(end), 2.0);
            self.verifyLessThan(dTightError, dLooseError);
            self.verifyGreaterThan(strTightStatistics.ui32RejectedSteps, ...
                uint32(0));
            self.verifyEqual(strTightStatistics.ui32FunctionEvaluations, ...
                uint32(6) * (strTightStatistics.ui32AcceptedSteps + ...
                strTightStatistics.ui32RejectedSteps));
        end

        function testGeneralPropagatorDispatchesRK4AndRK8(self)
            % The class-level host dispatcher must expose the same state-first
            % contract as the shared fixed-step provider.
            dxInitialState = [1.0; 0.0];

            [dxRK4History, dRK4Grid] = CGeneralPropagator.propagateState( ...
                @OscillatorLegacyRhs_, [0.0, 1.0], dxInitialState, ...
                dTimestep=0.3, enumOdeFunctioName="RK4");
            [dxRK8History, dRK8Grid] = CGeneralPropagator.propagateState( ...
                @OscillatorLegacyRhs_, [0.0, 1.0], dxInitialState, ...
                dTimestep=0.3, enumOdeFunctioName="RK8");

            [dxExpectedRK4History, dExpectedRK4Grid] = PropagateFixedStep( ...
                @OscillatorRhs_, [0.0, 1.0], dxInitialState, 0.3, ...
                struct(), struct(), EnumFixedStepScheme.RK4);
            [dxExpectedRK8History, dExpectedRK8Grid] = PropagateFixedStep( ...
                @OscillatorRhs_, [0.0, 1.0], dxInitialState, 0.3, ...
                struct(), struct(), EnumFixedStepScheme.RK8);

            self.verifyEqual(dxRK4History, dxExpectedRK4History);
            self.verifyEqual(dRK4Grid, dExpectedRK4Grid);
            self.verifyEqual(dxRK8History, dxExpectedRK8History);
            self.verifyEqual(dRK8Grid, dExpectedRK8Grid);
        end

        function testPropagatorsSupportBackwardAndZeroDuration(self)
            % Every interval provider must integrate backward and avoid all RHS
            % evaluations when the requested interval has zero duration.
            enumFixedSchemes = [EnumFixedStepScheme.RK2Heun, ...
                EnumFixedStepScheme.RK4, EnumFixedStepScheme.RK8];
            for ui32SchemeIndex = uint32(1):uint32(numel(enumFixedSchemes))
                [dxBackwardHistory, dBackwardGrid] = PropagateFixedStep( ...
                    @GrowthRhs_, [1.0, 0.0], exp(1.0), 0.1, ...
                    struct(), struct(), ...
                    enumFixedSchemes(double(ui32SchemeIndex)));

                self.verifyTrue(all(diff(dBackwardGrid) < 0.0));
                self.verifyEqual(dBackwardGrid([1, end]), [1.0; 0.0]);
                self.verifyLessThan(abs(dxBackwardHistory(end) - 1.0), ...
                    5.0e-3);
            end

            [dxAdaptiveHistory, dAdaptiveGrid] = PropagateAdaptiveStep( ...
                @GrowthRhs_, [1.0, 0.0], exp(1.0), 0.5, ...
                struct(), struct(), ...
                dRelativeTolerance=1.0e-10, ...
                dAbsoluteTolerance=1.0e-12);
            self.verifyTrue(all(diff(dAdaptiveGrid) < 0.0));
            self.verifyEqual(dAdaptiveGrid([1, end]), [1.0; 0.0]);
            self.verifyEqual(dxAdaptiveHistory(end), 1.0, 'AbsTol', 1.0e-9);

            for ui32SchemeIndex = uint32(1):uint32(numel(enumFixedSchemes))
                [dxZeroHistory, dZeroGrid, strZeroStatistics] = ...
                    PropagateFixedStep(@ErrorRhs_, [5.0, 5.0], ...
                    [1.0; 2.0], 0.2, struct(), struct(), ...
                    enumFixedSchemes(double(ui32SchemeIndex)));

                self.verifyEqual(dxZeroHistory, [1.0, 2.0]);
                self.verifyEqual(dZeroGrid, 5.0);
                self.verifyEqual(strZeroStatistics.ui32AcceptedSteps, ...
                    uint32(0));
                self.verifyEqual(strZeroStatistics.ui32FunctionEvaluations, ...
                    uint32(0));
            end

            [dxZeroHistory, dZeroGrid, strZeroStatistics] = ...
                PropagateAdaptiveStep(@ErrorRhs_, [5.0, 5.0], ...
                [1.0; 2.0], 0.2, struct(), struct());
            self.verifyEqual(dxZeroHistory, [1.0, 2.0]);
            self.verifyEqual(dZeroGrid, 5.0);
            self.verifyEqual(strZeroStatistics.ui32AcceptedSteps, uint32(0));
            self.verifyEqual(strZeroStatistics.ui32FunctionEvaluations, ...
                uint32(0));
        end

        function testInvalidInputsAndDerivativeDimensionsFailClearly(self)
            % Empty states, impossible adaptive bounds, and malformed RHS
            % outputs must fail at the owning propagation boundary.
            self.verifyError(@() PropagateFixedStep( ...
                @GrowthRhs_, [0.0, 1.0], zeros(0, 1), 0.1, ...
                struct(), struct(), EnumFixedStepScheme.RK4), ...
                'PropagateFixedStep:EmptyInitialState');
            self.verifyError(@() PropagateAdaptiveStep( ...
                @GrowthRhs_, [0.0, 1.0], 1.0, 0.1, ...
                struct(), struct(), ...
                dMinimumStep=0.2, dMaximumStep=0.1), ...
                'PropagateAdaptiveStep:InvalidStepBounds');
            self.verifyError(@() PropagateRK4Step( ...
                @WrongDimensionRhs_, 0.0, [1.0; 2.0], 0.1, ...
                struct(), struct()), ...
                'PropagateRK4Step:InvalidDerivative');
            self.verifyError(@() PropagateAdaptiveStep( ...
                @WrongDimensionRhs_, [0.0, 1.0], [1.0; 2.0], 0.1, ...
                struct(), struct()), ...
                'PropagateAdaptiveStep:InvalidDerivative');
        end

        function testRKF45FailsWhenMinimumStepCannotMeetTolerance(self)
            % The solver must reject an unsatisfied tolerance instead of
            % silently accepting a step at the configured lower bound.
            self.verifyError(@() PropagateAdaptiveStep( ...
                @GrowthRhs_, [0.0, 2.0], 1.0, 2.0, ...
                struct(), struct(), ...
                dRelativeTolerance=1.0e-14, ...
                dAbsoluteTolerance=1.0e-15, ...
                dMinimumStep=0.5), ...
                'PropagateAdaptiveStep:MinimumStepExceeded');
        end

        function testFixedSchemesMatchMatlabOdeSolvers(self)
            % Full fixed-step histories must agree with three tightly
            % configured independent MATLAB ODE implementations.
            dxInitialState = [0.4; -0.15];
            dDamping = 0.2;
            dForcing = 0.08;
            fcnReferenceDerivative = @(dTime, dxState) ForcedNonlinearRhs_( ...
                dTime, dxState, dDamping, dForcing);
            strDynParams = struct( ...
                'dDamping', dDamping, 'dForcing', dForcing);
            strModelConfigFlags = struct();

            enumFixedSchemes = [EnumFixedStepScheme.RK2Heun, ...
                EnumFixedStepScheme.RK4, EnumFixedStepScheme.RK8];
            dMaximumSteps = [0.005, 0.02, 0.1];
            dAbsoluteTolerances = [2.0e-6, 2.0e-9, 1.0e-12];
            dRelativeTolerances = [2.0e-6, 2.0e-9, 1.0e-12];

            for ui32SchemeIndex = uint32(1):uint32(numel(enumFixedSchemes))
                enumFixedStepScheme = ...
                    enumFixedSchemes(double(ui32SchemeIndex));
                [dxStateHistory, dTimeGrid] = PropagateFixedStep( ...
                    @ParameterizedNonlinearRhs_, [0.0, 2.0], dxInitialState, ...
                    dMaximumSteps(double(ui32SchemeIndex)), ...
                    strDynParams, strModelConfigFlags, ...
                    enumFixedStepScheme);
                dMaximumStep = dMaximumSteps(double(ui32SchemeIndex));
                self.verifyEqual(dTimeGrid([1, end]), [0.0; 2.0]);
                self.verifyTrue(all(diff(dTimeGrid) > 0.0));
                self.verifyLessThanOrEqual(max(diff(dTimeGrid)), ...
                    dMaximumStep + 128.0 * eps(2.0));

                [cellReferenceHistories, cellReferenceTimeGrids] = ...
                    EvaluateOdeReferences_( ...
                    fcnReferenceDerivative, dTimeGrid, dxInitialState);

                VerifyReferenceTimeGrids_(self, dTimeGrid, ...
                    cellReferenceTimeGrids);
                VerifyReferenceConsensus_(self, cellReferenceHistories);
                for ui32SolverIndex = uint32(1):uint32( ...
                        numel(cellReferenceHistories))
                    VerifyScaleAwareParity_(self, dxStateHistory, ...
                        cellReferenceHistories{double(ui32SolverIndex)}, ...
                        dAbsoluteTolerances(double(ui32SchemeIndex)), ...
                        dRelativeTolerances(double(ui32SchemeIndex)));
                end
            end
        end

        function testAdaptiveMatchesMatlabOdeSolversBothDirections(self)
            % Adaptive forward and backward histories must remain within a
            % bounded safety factor of the requested error-control settings.
            dxInitialState = [0.4; -0.15];
            dDamping = 0.2;
            dForcing = 0.08;
            fcnReferenceDerivative = @(dTime, dxState) ForcedNonlinearRhs_( ...
                dTime, dxState, dDamping, dForcing);
            strDynParams = struct( ...
                'dDamping', dDamping, 'dForcing', dForcing);
            strModelConfigFlags = struct();
            dRelativeTolerance = 1.0e-10;
            dAbsoluteTolerance = 1.0e-12;
            dParityAbsoluteTolerance = 5.0e-11;
            dParityRelativeTolerance = 5.0e-11;

            [dxForwardHistory, dForwardGrid] = PropagateAdaptiveStep( ...
                @ParameterizedNonlinearRhs_, [0.0, 2.0], dxInitialState, ...
                0.4, strDynParams, strModelConfigFlags, ...
                dRelativeTolerance=dRelativeTolerance, ...
                dAbsoluteTolerance=dAbsoluteTolerance);
            self.verifyEqual(dForwardGrid([1, end]), [0.0; 2.0]);
            self.verifyTrue(all(diff(dForwardGrid) > 0.0));
            [cellForwardReferences, cellForwardTimeGrids] = ...
                EvaluateOdeReferences_( ...
                fcnReferenceDerivative, dForwardGrid, dxInitialState);
            VerifyReferenceTimeGrids_(self, dForwardGrid, ...
                cellForwardTimeGrids);
            VerifyReferenceConsensus_(self, cellForwardReferences);

            for ui32SolverIndex = uint32(1):uint32( ...
                    numel(cellForwardReferences))
                VerifyScaleAwareParity_(self, dxForwardHistory, ...
                    cellForwardReferences{double(ui32SolverIndex)}, ...
                    dParityAbsoluteTolerance, ...
                    dParityRelativeTolerance);
            end

            dxBackwardInitialState = cellForwardReferences{3}(end, :).';
            [dxBackwardHistory, dBackwardGrid] = PropagateAdaptiveStep( ...
                @ParameterizedNonlinearRhs_, [2.0, 0.0], ...
                dxBackwardInitialState, 0.4, ...
                strDynParams, strModelConfigFlags, ...
                dRelativeTolerance=dRelativeTolerance, ...
                dAbsoluteTolerance=dAbsoluteTolerance);
            self.verifyEqual(dBackwardGrid([1, end]), [2.0; 0.0]);
            self.verifyTrue(all(diff(dBackwardGrid) < 0.0));
            [cellBackwardReferences, cellBackwardTimeGrids] = ...
                EvaluateOdeReferences_( ...
                fcnReferenceDerivative, dBackwardGrid, ...
                dxBackwardInitialState);
            VerifyReferenceTimeGrids_(self, dBackwardGrid, ...
                cellBackwardTimeGrids);
            VerifyReferenceConsensus_(self, cellBackwardReferences);

            for ui32SolverIndex = uint32(1):uint32( ...
                    numel(cellBackwardReferences))
                VerifyScaleAwareParity_(self, dxBackwardHistory, ...
                    cellBackwardReferences{double(ui32SolverIndex)}, ...
                    dParityAbsoluteTolerance, ...
                    dParityRelativeTolerance);
            end
        end

        function testGeneralPropagatorMatchesExplicitOdeGrid(self)
            % The dispatcher must preserve an irregular requested grid and
            % forward repeating RHS parameters to fixed and MATLAB solvers.
            dRequestedGrid = [0.0, 0.13, 0.31, 0.70, 1.15, 2.0];
            dxInitialState = [0.4; -0.15];
            dDamping = 0.2;
            dForcing = 0.08;
            fcnStateDerivative = @(dTime, dxState) ForcedNonlinearRhs_( ...
                dTime, dxState, dDamping, dForcing);
            [cellReferenceHistories, cellReferenceTimeGrids] = ...
                EvaluateOdeReferences_( ...
                fcnStateDerivative, dRequestedGrid, dxInitialState);
            VerifyReferenceTimeGrids_(self, dRequestedGrid, ...
                cellReferenceTimeGrids);

            [dxRK4History, dRK4Grid] = CGeneralPropagator.propagateState( ...
                @ForcedNonlinearRhs_, dRequestedGrid, dxInitialState, ...
                dDamping, dForcing, dTimestep=0.01, ...
                enumOdeFunctioName="RK4");
            self.verifyEqual(dRK4Grid, dRequestedGrid.');
            VerifyScaleAwareParity_(self, dxRK4History, ...
                cellReferenceHistories{3}, 5.0e-10, 5.0e-10);

            charOdeSolverNames = ["ode45", "ode78", "ode113"];
            for ui32SolverIndex = uint32(1):uint32( ...
                    numel(charOdeSolverNames))
                [dxDispatchedHistory, dDispatchedGrid] = ...
                    CGeneralPropagator.propagateState( ...
                    @ForcedNonlinearRhs_, dRequestedGrid, dxInitialState, ...
                    dDamping, dForcing, ...
                    objOdeOpts=BuildReferenceOdeOptions_(), ...
                    enumOdeFunctioName= ...
                    charOdeSolverNames(double(ui32SolverIndex)));

                self.verifyEqual(dDispatchedGrid, dRequestedGrid.');
                VerifyScaleAwareParity_(self, dxDispatchedHistory, ...
                    cellReferenceHistories{double(ui32SolverIndex)}, ...
                    5.0e-13, 5.0e-13);
            end
        end

        function testFixedStepCodegenRequiresConstantScheme(self)
            % A constant scheme must generate successfully, while exposing
            % the same scheme as a runtime entry-point input must be rejected.
            charCodegenRoot = tempname;
            mkdir(charCodegenRoot);
            objCodegenCleanup = onCleanup( ...
                @() rmdir(charCodegenRoot, 's'));

            objCodegenConfig = coder.config('lib');
            charConstantBuildDir = fullfile(charCodegenRoot, 'constant');
            codegen('-config', objCodegenConfig, ...
                '-d', charConstantBuildDir, ...
                'CodegenFixedStepSchemeProbe', ...
                '-args', {coder.Constant(EnumFixedStepScheme.RK4)});

            charRuntimeBuildDir = fullfile(charCodegenRoot, 'runtime');
            bRuntimeSchemeRejected = false;
            try
                codegen('-config', objCodegenConfig, ...
                    '-d', charRuntimeBuildDir, ...
                    'CodegenFixedStepSchemeProbe', ...
                    '-args', {EnumFixedStepScheme.RK4});
            catch
                bRuntimeSchemeRejected = true;
            end

            self.verifyTrue(bRuntimeSchemeRejected, ...
                ['Code generation must reject a runtime-variable fixed-step ', ...
                 'scheme.']);
            clear objCodegenCleanup
        end
    end
end

function dxDerivative = GrowthRhs_(dTime, dxState, ~, ~)
% Return exponential-growth dynamics.
dxDerivative = dxState + 0.0 * dTime;
end

function dxDerivative = ExplicitPayloadRhs_( ...
    dTime, dxState, strDynParams, strModelConfigFlags)
% Return a constant derivative that requires both explicit RHS inputs.
dSign = 1.0 - 2.0 * double(strModelConfigFlags.bNegateDerivative);
dxDerivative = dSign * strDynParams.dConstantDerivative * ...
    ones(size(dxState)) + 0.0 * dTime;
end

function dxDerivative = ErrorRhs_(~, dxState, ~, ~)
% Fail if a zero-duration propagator evaluates its derivative.
dxDerivative = dxState;
error('testNumericalPropagators:UnexpectedRhsEvaluation', ...
    'The RHS must not be evaluated for a zero-duration interval.');
end

function dxDerivative = OscillatorRhs_(dTime, dxState, ~, ~)
% Return a two-state harmonic-oscillator derivative.
dxDerivative = [dxState(2); -dxState(1)] + 0.0 * dTime;
end

function dxDerivative = OscillatorLegacyRhs_(dTime, dxState)
% Return oscillator dynamics for the legacy host-side dispatcher contract.
dxDerivative = [dxState(2); -dxState(1)] + 0.0 * dTime;
end

function dxDerivative = QuadraticGrowthRhs_(dTime, dxState, ~, ~)
% Return nonlinear autonomous dynamics with a closed-form solution.
dxDerivative = dxState.^2 + 0.0 * dTime;
end

function dxDerivative = TimeVaryingGrowthRhs_(dTime, dxState, ~, ~)
% Return explicitly time-dependent linear dynamics.
dxDerivative = dTime * dxState;
end

function dxDerivative = WrongDimensionRhs_(dTime, dxState, ~, ~)
% Return one fewer derivative element than the state contract requires.
dxDerivative = dxState(1:end-1) + 0.0 * dTime;
end

function dxDerivative = ParameterizedNonlinearRhs_( ...
    dTime, dxState, strDynParams, ~)
% Return nonlinear dynamics from the standard explicit dynamics payload.
dxDerivative = ForcedNonlinearRhs_(dTime, dxState, ...
    strDynParams.dDamping, strDynParams.dForcing);
end

function dxDerivative = ForcedNonlinearRhs_( ...
    dTime, dxState, dDamping, dForcing)
% Return a parameterized nonlinear oscillator without a closed-form solution.
dxDerivative = [dxState(2); ...
    -sin(dxState(1)) - dDamping * dxState(2) + ...
    dForcing * cos(0.7 * dTime)];
end

function [cellReferenceHistories, cellReferenceTimeGrids] = ...
    EvaluateOdeReferences_( ...
    fcnStateDerivative, dTimeGrid, dxInitialState)
% Evaluate every MATLAB ODE backend on the requested comparison timestamps.
cellOdeSolvers = {@ode45, @ode78, @ode113};
cellReferenceHistories = cell(size(cellOdeSolvers));
cellReferenceTimeGrids = cell(size(cellOdeSolvers));
strOdeOptions = BuildReferenceOdeOptions_();

for ui32SolverIndex = uint32(1):uint32(numel(cellOdeSolvers))
    [cellReferenceTimeGrids{double(ui32SolverIndex)}, ...
        cellReferenceHistories{double(ui32SolverIndex)}] = ...
        cellOdeSolvers{double(ui32SolverIndex)}( ...
        fcnStateDerivative, dTimeGrid, dxInitialState, strOdeOptions);
end
end

function strOdeOptions = BuildReferenceOdeOptions_()
% Configure MATLAB ODE references substantially tighter than parity bounds.
strOdeOptions = odeset('RelTol', 1.0e-12, 'AbsTol', 1.0e-14);
end

function VerifyReferenceConsensus_(self, cellReferenceHistories)
% Reject parity evidence when the independent MATLAB references disagree.
for ui32FirstSolver = uint32(1):uint32(numel(cellReferenceHistories) - 1)
    for ui32SecondSolver = ui32FirstSolver + uint32(1):uint32( ...
            numel(cellReferenceHistories))
        VerifyScaleAwareParity_(self, ...
            cellReferenceHistories{double(ui32FirstSolver)}, ...
            cellReferenceHistories{double(ui32SecondSolver)}, ...
            5.0e-12, 5.0e-12);
    end
end
end

function VerifyReferenceTimeGrids_( ...
    self, dRequestedTimeGrid, cellReferenceTimeGrids)
% Confirm every MATLAB ODE solver returns the requested timestamps unchanged.
dRequestedTimeGrid = dRequestedTimeGrid(:);
dTimeTolerance = 32.0 * eps(max(1.0, max(abs(dRequestedTimeGrid))));
for ui32SolverIndex = uint32(1):uint32(numel(cellReferenceTimeGrids))
    self.verifyEqual(cellReferenceTimeGrids{double(ui32SolverIndex)}, ...
        dRequestedTimeGrid, 'AbsTol', dTimeTolerance);
end
end

function VerifyScaleAwareParity_( ...
    self, dxActualHistory, dxReferenceHistory, ...
    dAbsoluteTolerance, dRelativeTolerance)
% Compare full histories through an element-wise absolute-plus-relative bound.
self.verifySize(dxActualHistory, size(dxReferenceHistory));
dAllowedDifference = dAbsoluteTolerance + ...
    dRelativeTolerance * abs(dxReferenceHistory);
dNormalizedDifference = abs(dxActualHistory - dxReferenceHistory) ./ ...
    dAllowedDifference;
self.verifyLessThanOrEqual(max(dNormalizedDifference, [], 'all'), 1.0);
end
