function [objAdvancedState, dAdvancedTime] = PropagateRK8StepAutoDiff( ...
    fcnStateDerivative, dCurrentTime, objCurrentState, dStepSize, ...
    strDynParams, strModelConfigFlags)
%% SIGNATURE
% [objAdvancedState, dAdvancedTime] = PropagateRK8StepAutoDiff( ...
%     fcnStateDerivative, dCurrentTime, objCurrentState, dStepSize, ...
%     strDynParams, strModelConfigFlags)
% -------------------------------------------------------------------------------------------------------------
%% DESCRIPTION
% Advance one numerical or CasADi symbolic state with the thirteen-stage
% Fehlberg eighth-order Runge-Kutta method. Double states delegate to the
% canonical code-generation-safe numerical kernel; CasADi SX/MX states build
% the equivalent differentiable stage graph without trajectory allocation.
% -------------------------------------------------------------------------------------------------------------
%% INPUT
% fcnStateDerivative  (1,1) function_handle using the standard four-input RHS contract
% dCurrentTime        (1,1) finite double current independent-variable value
% objCurrentState     (Nx1) finite double or CasADi SX/MX current state
% dStepSize           (1,1) finite double signed integration step
% strDynParams        (1,1) struct runtime dynamics payload forwarded to RHS
% strModelConfigFlags (1,1) struct model selection forwarded to RHS
% -------------------------------------------------------------------------------------------------------------
%% OUTPUT
% objAdvancedState    (Nx1) double or CasADi SX/MX state at the advanced time
% dAdvancedTime       (1,1) double advanced timestamp
% -------------------------------------------------------------------------------------------------------------
%% CHANGELOG
% 28-07-2026  Pietro Califano, Codex     Replace the legacy stub with numerical and symbolic RK8.
% -------------------------------------------------------------------------------------------------------------
%% DEPENDENCIES
% PropagateRK8Step
% -------------------------------------------------------------------------------------------------------------

arguments (Input)
    fcnStateDerivative (1,1) function_handle
    dCurrentTime (1,1) double {mustBeFinite}
    objCurrentState (:,1)
    dStepSize (1,1) double {mustBeFinite}
    strDynParams (1,1) struct
    strModelConfigFlags (1,1) struct
end

arguments (Output)
    objAdvancedState (:,1)
    dAdvancedTime (1,1) double
end

if isa(objCurrentState, 'double')
    % Reuse the canonical numerical implementation so the AutoDiff boundary
    % cannot drift from generated-code RK8 behavior.
    [objAdvancedState, dAdvancedTime] = PropagateRK8Step( ...
        fcnStateDerivative, dCurrentTime, objCurrentState, dStepSize, ...
        strDynParams, strModelConfigFlags);
    return;
end

ValidateSymbolicState_(objCurrentState);

% Evaluate the Fehlberg stages directly on the symbolic state graph.
objStage1 = fcnStateDerivative( ...
    dCurrentTime, objCurrentState, strDynParams, strModelConfigFlags);
ValidateDerivative_(objStage1, objCurrentState);

objStage2 = fcnStateDerivative( ...
    dCurrentTime + dStepSize * (2.0 / 27.0), ...
    objCurrentState + dStepSize * (2.0 / 27.0) * objStage1, ...
    strDynParams, strModelConfigFlags);
ValidateDerivative_(objStage2, objCurrentState);

objStage3 = fcnStateDerivative( ...
    dCurrentTime + dStepSize * (1.0 / 9.0), ...
    objCurrentState + dStepSize * ...
    ((1.0 / 36.0) * objStage1 + (1.0 / 12.0) * objStage2), ...
    strDynParams, strModelConfigFlags);
ValidateDerivative_(objStage3, objCurrentState);

objStage4 = fcnStateDerivative( ...
    dCurrentTime + dStepSize * (1.0 / 6.0), ...
    objCurrentState + dStepSize * ...
    ((1.0 / 24.0) * objStage1 + (1.0 / 8.0) * objStage3), ...
    strDynParams, strModelConfigFlags);
ValidateDerivative_(objStage4, objCurrentState);

objStage5 = fcnStateDerivative( ...
    dCurrentTime + dStepSize * (5.0 / 12.0), ...
    objCurrentState + dStepSize * ...
    ((5.0 / 12.0) * objStage1 - (25.0 / 16.0) * objStage3 + ...
     (25.0 / 16.0) * objStage4), strDynParams, strModelConfigFlags);
ValidateDerivative_(objStage5, objCurrentState);

objStage6 = fcnStateDerivative( ...
    dCurrentTime + dStepSize * (1.0 / 2.0), ...
    objCurrentState + dStepSize * ...
    ((1.0 / 20.0) * objStage1 + (1.0 / 4.0) * objStage4 + ...
     (1.0 / 5.0) * objStage5), strDynParams, strModelConfigFlags);
ValidateDerivative_(objStage6, objCurrentState);

objStage7 = fcnStateDerivative( ...
    dCurrentTime + dStepSize * (5.0 / 6.0), ...
    objCurrentState + dStepSize * ...
    (-(25.0 / 108.0) * objStage1 + (125.0 / 108.0) * objStage4 - ...
     (65.0 / 27.0) * objStage5 + (125.0 / 54.0) * objStage6), ...
    strDynParams, strModelConfigFlags);
ValidateDerivative_(objStage7, objCurrentState);

objStage8 = fcnStateDerivative( ...
    dCurrentTime + dStepSize * (1.0 / 6.0), ...
    objCurrentState + dStepSize * ...
    ((31.0 / 300.0) * objStage1 + (61.0 / 225.0) * objStage5 - ...
     (2.0 / 9.0) * objStage6 + (13.0 / 900.0) * objStage7), ...
    strDynParams, strModelConfigFlags);
ValidateDerivative_(objStage8, objCurrentState);

objStage9 = fcnStateDerivative( ...
    dCurrentTime + dStepSize * (2.0 / 3.0), ...
    objCurrentState + dStepSize * ...
    (2.0 * objStage1 - (53.0 / 6.0) * objStage4 + ...
     (704.0 / 45.0) * objStage5 - (107.0 / 9.0) * objStage6 + ...
     (67.0 / 90.0) * objStage7 + 3.0 * objStage8), ...
    strDynParams, strModelConfigFlags);
ValidateDerivative_(objStage9, objCurrentState);

objStage10 = fcnStateDerivative( ...
    dCurrentTime + dStepSize * (1.0 / 3.0), ...
    objCurrentState + dStepSize * ...
    (-(91.0 / 108.0) * objStage1 + (23.0 / 108.0) * objStage4 - ...
     (976.0 / 135.0) * objStage5 + (311.0 / 54.0) * objStage6 - ...
     (19.0 / 60.0) * objStage7 + (17.0 / 6.0) * objStage8 - ...
     (1.0 / 12.0) * objStage9), strDynParams, strModelConfigFlags);
ValidateDerivative_(objStage10, objCurrentState);

objStage11 = fcnStateDerivative(dCurrentTime + dStepSize, ...
    objCurrentState + dStepSize * ...
    ((2383.0 / 4100.0) * objStage1 - (341.0 / 164.0) * objStage4 + ...
     (4496.0 / 1025.0) * objStage5 - (301.0 / 82.0) * objStage6 + ...
     (2133.0 / 4100.0) * objStage7 + (45.0 / 82.0) * objStage8 + ...
     (45.0 / 164.0) * objStage9 + (18.0 / 41.0) * objStage10), ...
    strDynParams, strModelConfigFlags);
ValidateDerivative_(objStage11, objCurrentState);

objStage12 = fcnStateDerivative(dCurrentTime, ...
    objCurrentState + dStepSize * ...
    ((3.0 / 205.0) * objStage1 - (6.0 / 41.0) * objStage6 - ...
     (3.0 / 205.0) * objStage7 - (3.0 / 41.0) * objStage8 + ...
     (3.0 / 41.0) * objStage9 + (6.0 / 41.0) * objStage10), ...
    strDynParams, strModelConfigFlags);
ValidateDerivative_(objStage12, objCurrentState);

objStage13 = fcnStateDerivative(dCurrentTime + dStepSize, ...
    objCurrentState + dStepSize * ...
    (-(1777.0 / 4100.0) * objStage1 - (341.0 / 164.0) * objStage4 + ...
     (4496.0 / 1025.0) * objStage5 - (289.0 / 82.0) * objStage6 + ...
     (2193.0 / 4100.0) * objStage7 + (51.0 / 82.0) * objStage8 + ...
     (33.0 / 164.0) * objStage9 + (12.0 / 41.0) * objStage10 + ...
     objStage12), strDynParams, strModelConfigFlags);
ValidateDerivative_(objStage13, objCurrentState);

% Apply the eighth-order output weights without a numeric stage buffer.
objAdvancedState = objCurrentState + dStepSize * ...
    ((34.0 / 105.0) * objStage6 + (9.0 / 35.0) * objStage7 + ...
     (9.0 / 35.0) * objStage8 + (9.0 / 280.0) * objStage9 + ...
     (9.0 / 280.0) * objStage10 + (41.0 / 840.0) * objStage12 + ...
     (41.0 / 840.0) * objStage13);
dAdvancedTime = dCurrentTime + dStepSize;

end

function ValidateSymbolicState_(objCurrentState)
% Restrict the symbolic branch to differentiable CasADi graph types.
if ~(isa(objCurrentState, 'casadi.SX') || ...
        isa(objCurrentState, 'casadi.MX'))
    error('PropagateRK8StepAutoDiff:InvalidStateType', ...
        'The state must be a finite double column or a CasADi SX/MX column.');
end
if isempty(objCurrentState)
    error('PropagateRK8StepAutoDiff:EmptyState', ...
        'The current state must contain at least one element.');
end
end

function ValidateDerivative_(objDerivative, objReferenceState)
% Enforce state-sized numerical or symbolic RHS output at every stage.
bSupportedType = isa(objDerivative, 'double') || ...
    isa(objDerivative, 'casadi.DM') || ...
    isa(objDerivative, 'casadi.SX') || ...
    isa(objDerivative, 'casadi.MX');
if ~bSupportedType || ...
        ~isequal(size(objDerivative), size(objReferenceState))
    error('PropagateRK8StepAutoDiff:InvalidDerivative', ...
        'The state derivative must be a numerical or CasADi column matching the state size.');
end
if isa(objDerivative, 'double') && ~all(isfinite(objDerivative), 'all')
    error('PropagateRK8StepAutoDiff:InvalidDerivative', ...
        'A numerical state derivative must contain only finite values.');
end
end
