function dAccel_IN = EvalGaussMarkovAccel(dEvalTime, strProfile) %#codegen
arguments
    dEvalTime (1,1) double
    strProfile (1,1) struct
end
%% SIGNATURE
% dAccel_IN = EvalGaussMarkovAccel(dEvalTime, strProfile)
% -------------------------------------------------------------------------------------------------------------
%% DESCRIPTION
% Evaluate a pre-generated Gauss-Markov acceleration profile at an arbitrary timestamp. The between-grid value
% uses the stored segment innovation from GenerateGaussMarkovAccelSeq, so no random draw occurs inside the RHS.
% -------------------------------------------------------------------------------------------------------------
%% INPUT
% dEvalTime:  (1,1) double   Evaluation time in the same time scale as strProfile.dTimeGrid [TU].
% strProfile: (1,1) struct   Profile generated by GenerateGaussMarkovAccelSeq().
% -------------------------------------------------------------------------------------------------------------
%% OUTPUT
% dAccel_IN:  (3,1) double   Stochastic acceleration in inertial-frame components [LU/TU^2].
% -------------------------------------------------------------------------------------------------------------
%% CHANGELOG
% 01-07-2026    Pietro Califano, Codex 5.5      Add deterministic evaluation of pre-generated Gauss-Markov
%                                               residual acceleration profiles.
% -------------------------------------------------------------------------------------------------------------
%% DEPENDENCIES
% [-]
% -------------------------------------------------------------------------------------------------------------

dTimeGrid = strProfile.dTimeGrid;
dAccelGrid = strProfile.dAccelGrid;

if dEvalTime <= dTimeGrid(1)
    dAccel_IN = dAccelGrid(:,1);
    return
end

ui32NumSamples = uint32(numel(dTimeGrid));
if dEvalTime >= dTimeGrid(double(ui32NumSamples))
    dAccel_IN = dAccelGrid(:,double(ui32NumSamples));
    return
end

dRawSegmentIdx = floor((dEvalTime - dTimeGrid(1)) / strProfile.dTimeStep) + 1.0;

if dRawSegmentIdx < 1.0
    dRawSegmentIdx = 1.0;
elseif dRawSegmentIdx > double(ui32NumSamples - 1)
    dRawSegmentIdx = double(ui32NumSamples - 1);
end
ui32SegmentIdx = uint32(dRawSegmentIdx);

% Compute state transition matrix
dElapsed = dEvalTime - dTimeGrid(double(ui32SegmentIdx));
dPhi = exp(-dElapsed ./ strProfile.dTimeConst);

% Evaluate acceleration
dAccel_IN = strProfile.dMeanAccel + ...
    dPhi .* (dAccelGrid(:,double(ui32SegmentIdx)) - strProfile.dMeanAccel) + ...
    strProfile.dSigmaAccel .* sqrt(max(0.0, 1.0 - dPhi.^2)) .* ...
    strProfile.dStandardNormalInnovation(:,double(ui32SegmentIdx));

end
