classdef testDefineEnvironmentProperties < matlab.unittest.TestCase
    methods (Test)
        function testCarriesDatasetTargetAngularVelocity(testCase)
            dTimestamps = [0.0, 15.0, 40.0];
            dStateSC_IN = zeros(6, numel(dTimestamps));
            dDCM_TBfromIN = repmat(eye(3), 1, 1, numel(dTimestamps));
            dTargetPosition_IN = zeros(3, numel(dTimestamps));
            dSunPosition_IN = repmat([1.495978707e11; 0.0; 0.0], 1, numel(dTimestamps));
            dEarthPosition_IN = zeros(3, numel(dTimestamps));
            dTargetAngVel_IN = repmat([0.8e-4; -0.4e-4; 1.7e-4], 1, numel(dTimestamps));
            objDataset = SReferenceMissionDesign(EnumFrameName.IN, dTimestamps, dStateSC_IN, ...
                dDCM_TBfromIN, dTargetPosition_IN, dSunPosition_IN, dEarthPosition_IN, ...
                'dTargetAngVel_IN', dTargetAngVel_IN);

            [~, strMainBodyRefData] = DefineEnvironmentProperties(dTimestamps, ...
                "Itokawa", "J2000", objDataset=objDataset);

            testCase.verifyEqual(strMainBodyRefData.dAngVel_IN, dTargetAngVel_IN, 'AbsTol', 0.0);
        end

        function testBuildsSpacecraftPanelsAndPolyhedronGravityDataFromObj(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            charObjPath = fullfile(string(fixture.Folder), "cube_model.obj");
            [ui32Faces, dVerts] = testCase.buildCubeMesh();
            testCase.writeObjFile(charObjPath, ui32Faces, dVerts);

            dTimestamps = [0.0, 10.0];
            dStateSC_W = zeros(6, numel(dTimestamps));
            dDCM_TBfromW = repmat(eye(3), 1, 1, numel(dTimestamps));
            dTargetPosition_W = zeros(3, numel(dTimestamps));
            dSunPosition_W = repmat([1.495978707e11; 0; 0], 1, numel(dTimestamps));
            dEarthPosition_W = zeros(3, numel(dTimestamps));
            objDataset = SReferenceMissionDesign(EnumFrameName.IN, dTimestamps, dStateSC_W, ...
                dDCM_TBfromW, dTargetPosition_W, dSunPosition_W, dEarthPosition_W);

            strDynParamsSeed = struct();
            strDynParamsSeed.strSCdata = struct( ...
                'dReflCoeff', 1.2, ...
                'dSCmass', 10.0, ...
                'dA_SRP', 1.0);

            dDensity = 2000.0;
            dGravConst = 6.67430e-11;
            [strDynParams, ~, ~] = DefineEnvironmentProperties(dTimestamps, ...
                "Itokawa", ...
                "J2000", ...
                strDynParams=strDynParamsSeed, ...
                objDataset=objDataset, ...
                charSCpanelObjFilePath=charObjPath, ...
                dSCpanelDiffuseCoeff=0.25, ...
                dSCpanelSpecularCoeff=0.15, ...
                charPolyhedronGravityObjFilePath=charObjPath, ...
                dPolyhedronDensity=dDensity, ...
                dPolyhedronGravConst=dGravConst);

            strPanelData = strDynParams.strSCdata.strSRPpanelData;
            testCase.verifyEqual(strPanelData.ui32NumPanels, uint32(12));
            testCase.verifyEqual(sum(strPanelData.dSCquadsArea), 24.0, 'AbsTol', 1e-14);
            testCase.verifyEqual(strPanelData.dDiffSpecQuadsCoeffs, repmat([0.25, 0.15], 12, 1), 'AbsTol', 0.0);

            strPolyData = strDynParams.strMainData.strPolyhedronGravityData;
            testCase.verifyEqual(strPolyData.dVolume, 8.0, 'AbsTol', 1e-14);
            testCase.verifyEqual(strPolyData.dDensity, dDensity, 'AbsTol', 0.0);
            testCase.verifyEqual(strPolyData.dGravConst, dGravConst, 'AbsTol', 0.0);
            testCase.verifyEqual(strPolyData.dGravParam, dGravConst * dDensity * 8.0, 'RelTol', 1e-14);
            testCase.verifyEqual(size(strPolyData.ui32FaceVertexIds), [12, 3]);
            testCase.verifyGreaterThan(size(strPolyData.ui32EdgeVertexIds, 1), 0);
            testCase.verifyEqual([size(strPolyData.dEdgeDyadics, 1), size(strPolyData.dEdgeDyadics, 2)], [3, 3]);
            testCase.verifyEqual(size(strPolyData.dFaceDyadics), [3, 3, 12]);
        end
    end

    methods (Access = private)
        function [ui32Faces, dVerts] = buildCubeMesh(~)
            dVerts = [-1 -1 -1; ...
                       1 -1 -1; ...
                       1  1 -1; ...
                      -1  1 -1; ...
                      -1 -1  1; ...
                       1 -1  1; ...
                       1  1  1; ...
                      -1  1  1];

            ui32Faces = uint32([1 4 3; ...
                                1 3 2; ...
                                5 6 7; ...
                                5 7 8; ...
                                2 7 6; ...
                                2 3 7; ...
                                1 5 8; ...
                                1 8 4; ...
                                4 7 3; ...
                                4 8 7; ...
                                1 2 6; ...
                                1 6 5]);
        end

        function writeObjFile(~, charObjPath, ui32Faces, dVerts)
            fid = fopen(char(charObjPath), "w");
            assert(fid ~= -1, "testDefineEnvironmentProperties:FileOpenFailed", ...
                "Failed to create temporary OBJ file: %s", char(charObjPath));
            cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>

            for idVert = 1:size(dVerts, 1)
                fprintf(fid, "v %.16g %.16g %.16g\n", dVerts(idVert, 1), dVerts(idVert, 2), dVerts(idVert, 3));
            end

            for idFace = 1:size(ui32Faces, 1)
                fprintf(fid, "f %u %u %u\n", ui32Faces(idFace, 1), ui32Faces(idFace, 2), ui32Faces(idFace, 3));
            end
        end
    end
end
