function [dxAdvancedState, dAdvancedTime] = PropagateRK8Step( ...
    fcnStateDerivative, dCurrentTime, dxCurrentState, dStepSize) %#codegen
%% SIGNATURE
% [dxAdvancedState, dAdvancedTime] = PropagateRK8Step( ...
%     fcnStateDerivative, dCurrentTime, dxCurrentState, dStepSize)
% -------------------------------------------------------------------------------------------------------------
%% DESCRIPTION
% Advance one state with the thirteen-stage Fehlberg explicit eighth-order
% Runge-Kutta scheme. The signed step controls propagation direction; no
% trajectory storage is allocated.
% -------------------------------------------------------------------------------------------------------------
%% INPUT
% fcnStateDerivative  (1,1) function_handle returning a state-sized column
% dCurrentTime        (1,1) double current independent-variable value
% dxCurrentState      (Nx1) double current state
% dStepSize           (1,1) double signed integration step
% -------------------------------------------------------------------------------------------------------------
%% OUTPUT
% dxAdvancedState     (Nx1) double state at the advanced timestamp
% dAdvancedTime       (1,1) double advanced timestamp
% -------------------------------------------------------------------------------------------------------------
%% CHANGELOG
% 27-07-2026  Pietro Califano, Codex     First shared SimulationGears implementation.
% -------------------------------------------------------------------------------------------------------------
%% DEPENDENCIES
% None.
% -------------------------------------------------------------------------------------------------------------

arguments (Input)
    fcnStateDerivative (1,1) function_handle
    dCurrentTime (1,1) double {mustBeFinite}
    dxCurrentState (:,1) double {mustBeFinite}
    dStepSize (1,1) double {mustBeFinite}
end

arguments (Output)
    dxAdvancedState (:,1) double
    dAdvancedTime (1,1) double
end

% Evaluate the Fehlberg stages at their matched intermediate states.
dStage1 = fcnStateDerivative(dCurrentTime, dxCurrentState);
ValidateDerivative_(dStage1, dxCurrentState);

dStage2 = fcnStateDerivative(dCurrentTime + dStepSize * (2.0 / 27.0), ...
    dxCurrentState + dStepSize * (2.0 / 27.0) * dStage1);
ValidateDerivative_(dStage2, dxCurrentState);

dStage3 = fcnStateDerivative(dCurrentTime + dStepSize * (1.0 / 9.0), ...
    dxCurrentState + dStepSize * ...
    ((1.0 / 36.0) * dStage1 + (1.0 / 12.0) * dStage2));
ValidateDerivative_(dStage3, dxCurrentState);

dStage4 = fcnStateDerivative(dCurrentTime + dStepSize * (1.0 / 6.0), ...
    dxCurrentState + dStepSize * ...
    ((1.0 / 24.0) * dStage1 + (1.0 / 8.0) * dStage3));
ValidateDerivative_(dStage4, dxCurrentState);

dStage5 = fcnStateDerivative(dCurrentTime + dStepSize * (5.0 / 12.0), ...
    dxCurrentState + dStepSize * ...
    ((5.0 / 12.0) * dStage1 - (25.0 / 16.0) * dStage3 + ...
     (25.0 / 16.0) * dStage4));
ValidateDerivative_(dStage5, dxCurrentState);

dStage6 = fcnStateDerivative(dCurrentTime + dStepSize * (1.0 / 2.0), ...
    dxCurrentState + dStepSize * ...
    ((1.0 / 20.0) * dStage1 + (1.0 / 4.0) * dStage4 + ...
     (1.0 / 5.0) * dStage5));
ValidateDerivative_(dStage6, dxCurrentState);

dStage7 = fcnStateDerivative(dCurrentTime + dStepSize * (5.0 / 6.0), ...
    dxCurrentState + dStepSize * ...
    (-(25.0 / 108.0) * dStage1 + (125.0 / 108.0) * dStage4 - ...
     (65.0 / 27.0) * dStage5 + (125.0 / 54.0) * dStage6));
ValidateDerivative_(dStage7, dxCurrentState);

dStage8 = fcnStateDerivative(dCurrentTime + dStepSize * (1.0 / 6.0), ...
    dxCurrentState + dStepSize * ...
    ((31.0 / 300.0) * dStage1 + (61.0 / 225.0) * dStage5 - ...
     (2.0 / 9.0) * dStage6 + (13.0 / 900.0) * dStage7));
ValidateDerivative_(dStage8, dxCurrentState);

dStage9 = fcnStateDerivative(dCurrentTime + dStepSize * (2.0 / 3.0), ...
    dxCurrentState + dStepSize * ...
    (2.0 * dStage1 - (53.0 / 6.0) * dStage4 + ...
     (704.0 / 45.0) * dStage5 - (107.0 / 9.0) * dStage6 + ...
     (67.0 / 90.0) * dStage7 + 3.0 * dStage8));
ValidateDerivative_(dStage9, dxCurrentState);

dStage10 = fcnStateDerivative(dCurrentTime + dStepSize * (1.0 / 3.0), ...
    dxCurrentState + dStepSize * ...
    (-(91.0 / 108.0) * dStage1 + (23.0 / 108.0) * dStage4 - ...
     (976.0 / 135.0) * dStage5 + (311.0 / 54.0) * dStage6 - ...
     (19.0 / 60.0) * dStage7 + (17.0 / 6.0) * dStage8 - ...
     (1.0 / 12.0) * dStage9));
ValidateDerivative_(dStage10, dxCurrentState);

dStage11 = fcnStateDerivative(dCurrentTime + dStepSize, ...
    dxCurrentState + dStepSize * ...
    ((2383.0 / 4100.0) * dStage1 - (341.0 / 164.0) * dStage4 + ...
     (4496.0 / 1025.0) * dStage5 - (301.0 / 82.0) * dStage6 + ...
     (2133.0 / 4100.0) * dStage7 + (45.0 / 82.0) * dStage8 + ...
     (45.0 / 164.0) * dStage9 + (18.0 / 41.0) * dStage10));
ValidateDerivative_(dStage11, dxCurrentState);

dStage12 = fcnStateDerivative(dCurrentTime, ...
    dxCurrentState + dStepSize * ...
    ((3.0 / 205.0) * dStage1 - (6.0 / 41.0) * dStage6 - ...
     (3.0 / 205.0) * dStage7 - (3.0 / 41.0) * dStage8 + ...
     (3.0 / 41.0) * dStage9 + (6.0 / 41.0) * dStage10));
ValidateDerivative_(dStage12, dxCurrentState);

dStage13 = fcnStateDerivative(dCurrentTime + dStepSize, ...
    dxCurrentState + dStepSize * ...
    (-(1777.0 / 4100.0) * dStage1 - (341.0 / 164.0) * dStage4 + ...
     (4496.0 / 1025.0) * dStage5 - (289.0 / 82.0) * dStage6 + ...
     (2193.0 / 4100.0) * dStage7 + (51.0 / 82.0) * dStage8 + ...
     (33.0 / 164.0) * dStage9 + (12.0 / 41.0) * dStage10 + ...
     dStage12));
ValidateDerivative_(dStage13, dxCurrentState);

% Combine the stages with the Fehlberg eighth-order output weights.
dxAdvancedState = dxCurrentState + dStepSize * ...
    ((34.0 / 105.0) * dStage6 + (9.0 / 35.0) * dStage7 + ...
     (9.0 / 35.0) * dStage8 + (9.0 / 280.0) * dStage9 + ...
     (9.0 / 280.0) * dStage10 + (41.0 / 840.0) * dStage12 + ...
     (41.0 / 840.0) * dStage13);
dAdvancedTime = dCurrentTime + dStepSize;

end

function ValidateDerivative_(dxDerivative, dxReferenceState)
% Enforce the public RHS dimension and finite-value contract.
if ~isa(dxDerivative, 'double') || ...
        ~isequal(size(dxDerivative), size(dxReferenceState)) || ...
        ~all(isfinite(dxDerivative), 'all')
    error('PropagateRK8Step:InvalidDerivative', ...
        'The state derivative must be a finite double column matching the state size.');
end
end
