classdef testEvalRHS_InertialDynMaxFidelity < matlab.unittest.TestCase
    methods (Test)
        function testMatchesOrbitRHSWhenPerturbationsDisabled(testCase)
            dxState = [4; 0; 0; 0; 0.2; 0];
            strDynParams = testCase.buildDynParams();
            strModelConfigFlags = struct('bIncludeThirdBodies', false, ...
                              'bIncludeSRP', false, ...
                              'bIncludeSphericalHarmonics', false);

            dxMax = evalRHS_InertialDynMaxFidelity(0.0, dxState, strDynParams, strModelConfigFlags);
            dxOrbit = evalRHS_InertialDynOrbit(dxState, eye(3), ...
                                               strDynParams.strMainData.dGM, ...
                                               strDynParams.strMainData.dRefRadius, ...
                                               [], [], [], [], uint32(0));

            testCase.verifyEqual(dxMax, dxOrbit, 'AbsTol', 0.0);
        end

        function testAllZeroSphericalHarmonicsPayloadIsValid(testCase)
            dxState = [7200.0; 300.0; -200.0; 0.0; 7.2; 0.1];
            strDynParams = testCase.buildDynParams();
            strDynParams.strMainData.dSHcoeff = zeros(4, 2);
            strDynParams.strMainData.ui16MaxSHdegree = uint16(2);
            strModelConfigFlags = struct('bIncludeThirdBodies', false, ...
                                         'bIncludeSRP', false, ...
                                         'bIncludeSphericalHarmonics', true);

            dxWithZeroSH = evalRHS_InertialDynMaxFidelity(0.0, dxState, strDynParams, strModelConfigFlags);

            strDynParams.strMainData.dSHcoeff = [];
            strDynParams.strMainData.ui16MaxSHdegree = uint16(0);
            dxCentral = evalRHS_InertialDynMaxFidelity(0.0, dxState, strDynParams, strModelConfigFlags);

            testCase.verifyEqual(dxWithZeroSH, dxCentral, 'AbsTol', 1e-14);
        end

        function testNonEmptySphericalHarmonicsRequiresValidDegree(testCase)
            dxState = [7200.0; 300.0; -200.0; 0.0; 7.2; 0.1];
            strModelConfigFlags = struct('bIncludeThirdBodies', false, ...
                                         'bIncludeSRP', false, ...
                                         'bIncludeSphericalHarmonics', true);

            strDynParamsMissingDegree = testCase.buildDynParams();
            strDynParamsMissingDegree.strMainData.dSHcoeff = zeros(4, 2);
            strDynParamsMissingDegree.strMainData = rmfield(strDynParamsMissingDegree.strMainData, 'ui16MaxSHdegree');

            testCase.verifyError(@() evalRHS_InertialDynMaxFidelity(0.0, dxState, ...
                strDynParamsMissingDegree, strModelConfigFlags), ...
                'ResolveInertialDynMaxFidelityConfig:MissingSHDegree');

            strDynParamsInvalidDegree = testCase.buildDynParams();
            strDynParamsInvalidDegree.strMainData.dSHcoeff = zeros(4, 2);
            strDynParamsInvalidDegree.strMainData.ui16MaxSHdegree = uint16(1);

            testCase.verifyError(@() evalRHS_InertialDynMaxFidelity(0.0, dxState, ...
                strDynParamsInvalidDegree, strModelConfigFlags), ...
                'ResolveInertialDynMaxFidelityConfig:InvalidSHDegree');
        end

        function testThirdBodyToggles(testCase)
            dxState = [1; 0; 0; 0; 0; 0];
            strDynParams = testCase.buildDynParams();
            strDynParams.strMainData.dGM = 0.0;
            strModelConfigFlagsOff = struct('bIncludeThirdBodies', false, 'bIncludeSRP', false, 'bIncludeSphericalHarmonics', false);
            strModelConfigFlagsOn = struct('bIncludeSunThirdBody', true, ...
                                'bIncludeEarthThirdBody', true, ...
                                'bIncludeSRP', false, ...
                                'bIncludeSphericalHarmonics', false);

            [dxOff, strInfoOff] = evalRHS_InertialDynMaxFidelity(0.0, dxState, strDynParams, strModelConfigFlagsOff);
            [dxOn, strInfoOn] = evalRHS_InertialDynMaxFidelity(0.0, dxState, strDynParams, strModelConfigFlagsOn);

            testCase.verifyEqual(dxOff(4:6), zeros(3, 1), 'AbsTol', 0.0);
            testCase.verifyGreaterThan(norm(dxOn(4:6)), 0.0);
            testCase.verifyEqual(strInfoOff.d3rdBodiesGM, zeros(size(strInfoOff.d3rdBodiesGM)), 'AbsTol', 0.0);
            testCase.verifyEqual(strInfoOn.d3rdBodiesGM(1:2), [strDynParams.strBody3rdData(1:2).dGM].', 'AbsTol', 0.0);
        end

        function testCannonballSRPDistanceScalingAndEclipse(testCase)
            strDynParams = testCase.buildDynParams();
            strDynParams.strMainData.dGM = 0.0;
            strDynParams.strBody3rdData(1).dGM = 0.0;
            strDynParams.strBody3rdData(2).dGM = 0.0;
            strModelConfigFlags = struct('bIncludeSunThirdBody', false, ...
                              'bIncludeEarthThirdBody', false, ...
                              'bIncludeSRP', true, ...
                              'bIncludeEclipse', false, ...
                              'bIncludeSphericalHarmonics', false);

            dxNear = evalRHS_InertialDynMaxFidelity(0.0, [1; 0; 0; 0; 0; 0], strDynParams, strModelConfigFlags);
            strDynParams.strBody3rdData(1).strOrbitData.dChbvPolycoeffs = testCase.constantChebPosition([21; 0; 0]);
            dxFar = evalRHS_InertialDynMaxFidelity(0.0, [1; 0; 0; 0; 0; 0], strDynParams, strModelConfigFlags);

            testCase.verifyEqual(dxNear(4), -8.0, 'AbsTol', 1e-14);
            testCase.verifyEqual(dxFar(4), -2.0, 'AbsTol', 1e-14);

            strModelConfigFlags.bIncludeEclipse = true;
            strDynParams.strBody3rdData(1).strOrbitData.dChbvPolycoeffs = testCase.constantChebPosition([10; 0; 0]);
            [dxEclipse, strInfo] = evalRHS_InertialDynMaxFidelity(0.0, [-2; 0; 0; 0; 0; 0], strDynParams, strModelConfigFlags);

            testCase.verifyTrue(strInfo.bIsInEclipse);
            testCase.verifyEqual(dxEclipse(4:6), zeros(3, 1), 'AbsTol', 0.0);
        end

        function testLegacyFixedPressureSRPDefaultsWithoutReferenceDistance(testCase)
            dxState = [1; 0; 0; 0; 0; 0];
            strDynParams = testCase.buildDynParams();
            strDynParams.strSRPdata = struct('dP_SRP', 4.0);
            strModelConfigFlags = struct('bIncludeMainGravity', false, ...
                                         'bIncludeThirdBodies', false, ...
                                         'bIncludeSunThirdBody', false, ...
                                         'bIncludeEarthThirdBody', false, ...
                                         'bIncludeSRP', true, ...
                                         'bIncludeEclipse', false, ...
                                         'bUsePanelSRP', false, ...
                                         'bIncludeSphericalHarmonics', false, ...
                                         'bIncludePolyhedronGravity', false);

            [dDxDt, strAccelInfo] = evalRHS_InertialDynMaxFidelity(0.0, ...
                dxState, strDynParams, strModelConfigFlags);
            dDynMatrix = evalJac_InertialDynMaxFidelity(0.0, ...
                dxState, strDynParams, strModelConfigFlags, strAccelInfo);

            testCase.verifyEqual(dDxDt(4:6), [-8; 0; 0], 'AbsTol', 1e-14);
            testCase.verifyEqual(dDynMatrix(4:6, 1:3), diag([0.0, 0.8, 0.8]), ...
                'AbsTol', 1e-14);
        end

        function testPanelSRPSelectedOnlyWhenPanelDataExists(testCase)
            strDynParams = testCase.buildDynParams();
            strDynParams.strMainData.dGM = 0.0;
            strDynParams.strBody3rdData(1).dGM = 0.0;
            strDynParams.strBody3rdData(2).dGM = 0.0;
            strDynParams.strSRPdata.bRecomputePressureFromDistance = false;
            strModelConfigFlags = struct('bIncludeSunThirdBody', false, ...
                              'bIncludeEarthThirdBody', false, ...
                              'bIncludeSRP', true, ...
                              'bIncludeEclipse', false, ...
                              'bUsePanelSRP', true, ...
                              'bIncludeSphericalHarmonics', false, ...
                              'bRecomputeSRPpressureFromDistance', true);

            [dxCannonball, strInfoCannonball] = evalRHS_InertialDynMaxFidelity(0.0, ...
                [1; 0; 0; 0; 0; 0], strDynParams, strModelConfigFlags);
            testCase.verifyTrue(strInfoCannonball.bCannonballSRPSelected);
            testCase.verifyFalse(strInfoCannonball.bPanelSRPSelected);

            strDynParams.strSCdata.strSRPpanelData = struct( ...
                'dSCquadsArea', 2.0, ...
                'dDiffSpecQuadsCoeffs', [0.0 0.0], ...
                'dQuadsNormals_SCB', [1; 0; 0], ...
                'dQuadsPressCentre_SCB', [0; 0; 0], ...
                'charLengthUnit', 'm');
            strDynParams.strSCdata.dA_SRP = 999.0;

            [dxPanel, strInfoPanel] = evalRHS_InertialDynMaxFidelity(0.0, ...
                [1; 0; 0; 0; 0; 0], strDynParams, strModelConfigFlags);

            testCase.verifyTrue(strInfoPanel.bPanelSRPSelected);
            testCase.verifyFalse(strInfoPanel.bCannonballSRPSelected);
            testCase.verifyEqual(strInfoPanel.dAccCannonBallSRP, zeros(3, 1), 'AbsTol', 0.0);
            testCase.verifyGreaterThan(norm(strInfoPanel.dAccPanelSRP_IN), 0.0);
            testCase.verifyNotEqual(dxPanel(4:6), dxCannonball(4:6));
        end

        function testPolyhedronGravityMatchesExactEvaluator(testCase)
            [ui32Faces, dVerts] = testCase.buildCubeMesh();
            [ui32Edges, dEe, dFf] = ComputePolyhedronFaceEdgeData(ui32Faces, dVerts);
            [dVolume, ~] = ComputeMeshModelVolumeAndCoM(ui32Faces, dVerts);

            dDensity = 2000.0;
            dGravConst = 6.67430e-11;
            dGravParam = dGravConst * dDensity * dVolume;

            strDynParams = testCase.buildDynParams();
            strDynParams.strMainData.dGM = dGravParam;
            strDynParams.strMainData.dRefRadius = 1.0;
            strDynParams.strMainData.dSHcoeff = [];
            strDynParams.strMainData.ui16MaxSHdegree = uint16(0);
            strDynParams.strMainData.strPolyhedronGravityData = struct( ...
                'ui32FaceVertexIds', ui32Faces, ...
                'dVerticesPos', dVerts, ...
                'dDensity', dDensity, ...
                'ui32EdgeVertexIds', ui32Edges, ...
                'dEdgeDyadics', dEe, ...
                'dFaceDyadics', dFf, ...
                'dGravConst', dGravConst, ...
                'dGravParam', dGravParam);

            strModelConfigFlags = struct('bIncludeThirdBodies', false, ...
                              'bIncludeSRP', false, ...
                              'bIncludeSphericalHarmonics', false);
            dxState = [4.0; 0.3; -0.2; 0.0; 0.0; 0.0];

            [dDxDt, strInfo] = evalRHS_InertialDynMaxFidelity(0.0, dxState, strDynParams, strModelConfigFlags);
            dAccPolyTotal = EvalPolyhedronGrav(dxState(1:3), ...
                ui32Faces, dVerts, dDensity, ui32Edges, dEe, dFf, dGravConst);
            dAccCentral = -dGravParam * dxState(1:3) / norm(dxState(1:3))^3;

            testCase.verifyEqual(dDxDt(4:6), dAccPolyTotal, 'RelTol', 1e-12, 'AbsTol', 1e-18);
            testCase.verifyEqual(strInfo.dAccPolyhedronPert_IN, dAccPolyTotal - dAccCentral, ...
                'RelTol', 1e-12, 'AbsTol', 1e-18);
        end
    end

    methods (Access = private)
        function strDynParams = buildDynParams(testCase)
            strDynParams = struct();
            strDynParams.strMainData = struct('dGM', 1.0, ...
                                              'dRefRadius', 1.0, ...
                                              'dSHcoeff', zeros(4, 2), ...
                                              'ui16MaxSHdegree', uint16(2));
            strDynParams.strBody3rdData(1).dGM = 3.0;
            strDynParams.strBody3rdData(1).dRefRadius = 696000.0;
            strDynParams.strBody3rdData(1).strOrbitData = testCase.constantOrbitData([11; 0; 0]);
            strDynParams.strBody3rdData(2).dGM = 5.0;
            strDynParams.strBody3rdData(2).dRefRadius = 6378.0;
            strDynParams.strBody3rdData(2).strOrbitData = testCase.constantOrbitData([0; 13; 0]);
            strDynParams.strSRPdata = struct('dP_SRP0', 4.0, ...
                                             'dP_SRP', 4.0, ...
                                             'dReferenceDistance', 10.0, ...
                                             'bRecomputePressureFromDistance', true);
            strDynParams.strSCdata = struct('dReflCoeff', 1.0, ...
                                            'dSCmass', 1.0, ...
                                            'dA_SRP', 2.0);
        end

        function strOrbitData = constantOrbitData(testCase, dPosition)
            strOrbitData = struct('ui32PolyDeg', uint32(2), ...
                                  'dChbvPolycoeffs', testCase.constantChebPosition(dPosition), ...
                                  'dTimeLowBound', -100.0, ...
                                  'dTimeUpBound', 100.0);
        end

        function dCoeffs = constantChebPosition(~, dPosition)
            dCoeffs = [dPosition(1); 0; 0; ...
                       dPosition(2); 0; 0; ...
                       dPosition(3); 0; 0];
        end

        function [ui32Faces, dVerts] = buildCubeMesh(~)
            dVerts = [-1 -1 -1; ...
                       1 -1 -1; ...
                       1  1 -1; ...
                      -1  1 -1; ...
                      -1 -1  1; ...
                       1 -1  1; ...
                       1  1  1; ...
                      -1  1  1];

            ui32Faces = uint32([1 4 3; ...
                                1 3 2; ...
                                5 6 7; ...
                                5 7 8; ...
                                2 7 6; ...
                                2 3 7; ...
                                1 5 8; ...
                                1 8 4; ...
                                4 7 3; ...
                                4 8 7; ...
                                1 2 6; ...
                                1 6 5]);
        end
    end
end
