classdef testEvalJac_InertialDynMaxFidelityPanelSRP < matlab.unittest.TestCase
    %% DESCRIPTION
    % Regression tests for panel SRP linearization in the max-fidelity inertial dynamics Jacobian.
    % -------------------------------------------------------------------------------------------------------------

    methods (Test)
        function testPanelSRPJacobianMatchesRhsFiniteDifference(testCase)
            dxState = [1.0; -0.5; 0.3; 0.0; 0.0; 0.0];
            strDynParams = testCase.buildPanelDynParams(dxState(1:3));
            strModelConfigFlags = testCase.buildPanelModelFlags();

            dJacAnalytical = evalJac_InertialDynMaxFidelity(0.0, ...
                                                            dxState, ...
                                                            strDynParams, ...
                                                            strModelConfigFlags);
            dJacFD = testCase.finiteDifferenceRhsJacobian(dxState, ...
                                                          strDynParams, ...
                                                          strModelConfigFlags);

            testCase.verifyEqual(dJacAnalytical(4:6, 1:3), dJacFD, 'RelTol', 2e-5, 'AbsTol', 2e-10);
        end
    end

    methods (Access = private)
        function strModelConfigFlags = buildPanelModelFlags(~)
            strModelConfigFlags = struct('bIncludeMainGravity', false, ...
                                         'bIncludeSunThirdBody', false, ...
                                         'bIncludeEarthThirdBody', false, ...
                                         'bIncludeSRP', true, ...
                                         'bIncludeEclipse', false, ...
                                         'bUsePanelSRP', true, ...
                                         'bIncludeSphericalHarmonics', false, ...
                                         'bRecomputeSRPpressureFromDistance', true);
        end

        function strDynParams = buildPanelDynParams(testCase, dPosSC_IN)
            dSunPos_IN = [11.0; 4.0; 3.0];
            dQuat_INfromSCB = [1; 0; 0; 0];
            dSCtoSun_IN = dSunPos_IN - dPosSC_IN;
            dSunDir_SCB = dSCtoSun_IN / norm(dSCtoSun_IN);

            dTangent1 = [0; 1; 0] - dSunDir_SCB * dot([0; 1; 0], dSunDir_SCB);
            dTangent1 = dTangent1 / norm(dTangent1);
            dTangent2 = cross(dSunDir_SCB, dTangent1);
            dNormals_SCB = [dSunDir_SCB + 0.30 * dTangent1, ...
                            dSunDir_SCB - 0.20 * dTangent1 + 0.25 * dTangent2, ...
                            -dSunDir_SCB];
            dNormals_SCB = dNormals_SCB ./ vecnorm(dNormals_SCB, 2, 1);

            strDynParams = struct();
            strDynParams.strMainData = struct('dGM', 0.0, ...
                                              'dRefRadius', 0.0, ...
                                              'dSHcoeff', [], ...
                                              'ui16MaxSHdegree', uint16(0));
            strDynParams.strBody3rdData(1).dGM = 0.0;
            strDynParams.strBody3rdData(1).dRefRadius = 0.0;
            strDynParams.strBody3rdData(1).strOrbitData = testCase.constantOrbitData(dSunPos_IN);
            strDynParams.strBody3rdData(2).dGM = 0.0;
            strDynParams.strBody3rdData(2).dRefRadius = 0.0;
            strDynParams.strBody3rdData(2).strOrbitData = testCase.constantOrbitData([0; 0; 0]);
            strDynParams.strSRPdata = struct('dP_SRP0', 4.0, ...
                                             'dP_SRP', 4.0, ...
                                             'dReferenceDistance', 10.0, ...
                                             'bRecomputePressureFromDistance', true);
            strDynParams.strSCdata = struct('dReflCoeff', 1.0, ...
                                            'dSCmass', 7.0, ...
                                            'dA_SRP', 99.0, ...
                                            'dqSCBwrtIN', dQuat_INfromSCB, ...
                                            'dCoMpos_SCB', zeros(3, 1));
            strDynParams.strSCdata.strSRPpanelData = struct( ...
                'dSCquadsArea', [1.1; 0.7; 0.5], ...
                'dDiffSpecQuadsCoeffs', [0.2, 0.1; 0.4, 0.25; 0.6, 0.2], ...
                'dQuadsNormals_SCB', dNormals_SCB, ...
                'dQuadsPressCentre_SCB', zeros(3, 3), ...
                'charLengthUnit', 'm');
        end

        function dJacFD = finiteDifferenceRhsJacobian(~, dxState, strDynParams, strModelConfigFlags)
            dStep = 1e-4;
            dJacFD = zeros(3, 3);

            for idAxis = 1:3
                dxPerturb = zeros(6, 1);
                dxPerturb(idAxis) = dStep;

                dDxDtPlus = evalRHS_InertialDynMaxFidelity(0.0, ...
                                                           dxState + dxPerturb, ...
                                                           strDynParams, ...
                                                           strModelConfigFlags);
                dDxDtMinus = evalRHS_InertialDynMaxFidelity(0.0, ...
                                                            dxState - dxPerturb, ...
                                                            strDynParams, ...
                                                            strModelConfigFlags);

                dJacFD(:, idAxis) = (dDxDtPlus(4:6) - dDxDtMinus(4:6)) / (2.0 * dStep);
            end
        end

        function strOrbitData = constantOrbitData(testCase, dPosition)
            strOrbitData = struct('ui32PolyDeg', uint32(2), ...
                                  'dChbvPolycoeffs', testCase.constantChebPosition(dPosition), ...
                                  'dTimeLowBound', -100.0, ...
                                  'dTimeUpBound', 100.0);
        end

        function dCoeffs = constantChebPosition(~, dPosition)
            dCoeffs = [dPosition(1); 0; 0; ...
                       dPosition(2); 0; 0; ...
                       dPosition(3); 0; 0];
        end
    end
end
