function dxdt = RHS_CR3BP(x, mu)
%RHS_CR3BP
%    dxdt = RHS_CR3BP(X, MU)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    19-Oct-2022 14:34:49

x1 = x(1,:);
x2 = x(2,:);
x3 = x(3,:);
x4 = x(4,:);
x5 = x(5,:);
x6 = x(6,:);
t2 = mu+x1;
t3 = mu.*2.0;
t4 = x1.*2.0;
t5 = x2.^2;
t6 = x3.^2;
t7 = mu-1.0;
t8 = t2-1.0;
t9 = t2.^2;
t10 = t8.^2;
t11 = t5+t6+t9;
t12 = t5+t6+t10;
t13 = 1.0./t11.^(3.0./2.0);
t14 = 1.0./t12.^(3.0./2.0);
dxdt = [x4;x5;x6;x1+x5.*2.0-mu.*t8.*t14+t2.*t7.*t13;x2-x4.*2.0-mu.*t14.*x2+t7.*t13.*x2;-mu.*t14.*x3+t7.*t13.*x3];
