function dxdt = RHS_PBR4BP_planar(x,mu,t)
%RHS_PBR4BP_planar
%    RHS = RHS_PBR4BP_planar(IN1,MU,T)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    20-Oct-2022 17:04:06

x1 = x(1,:);
x2 = x(2,:);
x3 = x(3,:);
x4 = x(4,:);
t2 = mu+x1;
t3 = mu.*2.0;
t4 = x1.*2.0;
t5 = x2.^2;
t6 = mu-1.0;
t14 = t.*9.25195985e-1;
t7 = t2-1.0;
t8 = t2.^2;
t15 = cos(t14);
t16 = sin(t14);
t9 = t7.^2;
t10 = t5+t8;
t17 = t15.*3.88811143e+2;
t18 = t16.*3.88811143e+2;
t11 = t5+t9;
t12 = 1.0./t10.^(3.0./2.0);
t19 = -t17;
t20 = t18+x2;
t23 = (t17-x1).^2;
t13 = 1.0./t11.^(3.0./2.0);
t21 = t19+x1;
t22 = t20.^2;
t24 = t22+t23;
t25 = 1.0./t24.^(3.0./2.0);
mt1 = [x3;x4;t15.*(-2.175640736698581)+x1+x4.*2.0-t25.*(t4-t15.*7.77622286e+2).*1.644502705e+5-mu.*t7.*t13+t2.*t6.*t12];
mt2 = [t16.*2.175640736698581+x2-x3.*2.0-t25.*(t16.*7.77622286e+2+x2.*2.0).*1.644502705e+5-mu.*t13.*x2+t6.*t12.*x2];
dxdt = [mt1;mt2];
