function dJacobian = EvalJac_PBR4BP_planar(dState, dMassRatio, dTime) %#codegen
arguments (Input)
    dState      (:,1) double {mustBeNumeric}
    dMassRatio  (1,1) double {mustBeNumeric, mustBePositive, mustBeLessThan(dMassRatio, 1)}
    dTime       (1,1) double {mustBeNumeric}
end
arguments (Output)
    dJacobian   (4,4) double
end
%% PROTOTYPE
% dJacobian = EvalJac_PBR4BP_planar(dState, dMassRatio, dTime)
% -------------------------------------------------------------------------------------------------------------
%% DESCRIPTION
% Analytical Jacobian of the planar Bi-circular Restricted Four-Body Problem equations of motion.
% Includes partial derivatives from the CR3BP terms and the Sun gravitational perturbation.
% Only positions (first 2 elements of dState) are used. See RHS_PBR4BP_planar for model description
% and constant definitions.
% -------------------------------------------------------------------------------------------------------------
%% INPUT
% dState       (:,1) double   State vector (at least 2 elements; only x,y used)
% dMassRatio   (1,1) double   Mass ratio m2/(m1+m2) of the two main primaries
% dTime        (1,1) double   Non-dimensional time
% -------------------------------------------------------------------------------------------------------------
%% OUTPUT
% dJacobian    (4,4) double   Jacobian of the planar PBR4BP
% -------------------------------------------------------------------------------------------------------------
%% CHANGELOG
% 20-10-2022    Symbolic Math Toolbox   Auto-generated version.
% 28-03-2026    Claude Code             Manual rewrite with readable variables.
% -------------------------------------------------------------------------------------------------------------
%% DEPENDENCIES
% [-]
% -------------------------------------------------------------------------------------------------------------

% Sun parameters (same as in RHS_PBR4BP_planar)
dSunAngRate   = 9.25195985e-1;
dSunDist      = 3.88811143e+2;
dSunGravParam = 3.289005410e+5;

dPosX = dState(1);
dPosY = dState(2);

dGravP1 = 1 - dMassRatio;
dGravP2 = dMassRatio;

% Relative positions to primaries
dRelX_P1 = dPosX + dMassRatio;
dRelX_P2 = dPosX - (1 - dMassRatio);

dDistP1_sq = dRelX_P1^2 + dPosY^2;
dDistP2_sq = dRelX_P2^2 + dPosY^2;

dInvDistP1 = 1.0 / sqrt(dDistP1_sq);
dInvDistP2 = 1.0 / sqrt(dDistP2_sq);
dInvDistP1_3 = dInvDistP1 / dDistP1_sq;
dInvDistP2_3 = dInvDistP2 / dDistP2_sq;
dInvDistP1_5 = dInvDistP1_3 / dDistP1_sq;
dInvDistP2_5 = dInvDistP2_3 / dDistP2_sq;
dGravP1OverDistP1_3 = dGravP1 * dInvDistP1_3;
dGravP2OverDistP2_3 = dGravP2 * dInvDistP2_3;
dScaleP1 = 3.0 * dGravP1 * dInvDistP1_5;
dScaleP2 = 3.0 * dGravP2 * dInvDistP2_5;

% Sun position in synodic frame.
% ACHTUNG: The legacy autogenerated model uses [R*cos(phase); -R*sin(phase)].
dSunPhase = dSunAngRate * dTime;
dSunPosX = dSunDist * cos(dSunPhase);
dSunPosY = -dSunDist * sin(dSunPhase);

% Position relative to Sun
dRelX_Sun = dPosX - dSunPosX;
dRelY_Sun = dPosY - dSunPosY;
dDistSun_sq = dRelX_Sun^2 + dRelY_Sun^2;
dInvDistSun = 1.0 / sqrt(dDistSun_sq);
dInvDistSun_3 = dInvDistSun / dDistSun_sq;
dInvDistSun_5 = dInvDistSun_3 / dDistSun_sq;
dSunGravOverDistSun_3 = dSunGravParam * dInvDistSun_3;
dSunScale = 3.0 * dSunGravParam * dInvDistSun_5;

% CR3BP Hessian contribution
dSumInvCube = dGravP1OverDistP1_3 + dGravP2OverDistP2_3;

dUxx_CR3BP = 1 - dSumInvCube + dScaleP1 * dRelX_P1^2 + dScaleP2 * dRelX_P2^2;
dUyy_CR3BP = 1 - dSumInvCube + dScaleP1 * dPosY^2    + dScaleP2 * dPosY^2;
dUxy_CR3BP = dScaleP1 * dRelX_P1 * dPosY + dScaleP2 * dRelX_P2 * dPosY;

% Sun Hessian contribution: d/dxi(-ms*(xi-xSi)/rS^3) = -ms/rS^3 + 3*ms*(xi-xSi)*(xj-xSj)/rS^5
dUxx_Sun = -dSunGravOverDistSun_3 + dSunScale * dRelX_Sun^2;
dUyy_Sun = -dSunGravOverDistSun_3 + dSunScale * dRelY_Sun^2;
dUxy_Sun = dSunScale * dRelX_Sun * dRelY_Sun;

% Total Hessian
dUxx = dUxx_CR3BP + dUxx_Sun;
dUyy = dUyy_CR3BP + dUyy_Sun;
dUxy = dUxy_CR3BP + dUxy_Sun;

% Assemble 4x4 Jacobian
dJacobian = [0,    0,    1,  0;
             0,    0,    0,  1;
             dUxx, dUxy, 0,  2;
             dUxy, dUyy, -2, 0];

end
