function dxdt = RHS_PBR4BP_planar(dState, dMassRatio, dTime) %#codegen
arguments (Input)
    dState      (4,1) double {mustBeNumeric}
    dMassRatio  (1,1) double {mustBeNumeric, mustBePositive, mustBeLessThan(dMassRatio, 1)}
    dTime       (1,1) double {mustBeNumeric}
end
arguments (Output)
    dxdt        (4,1) double
end
%% PROTOTYPE
% dxdt = RHS_PBR4BP_planar(dState, dMassRatio, dTime)
% -------------------------------------------------------------------------------------------------------------
%% DESCRIPTION
% Right-hand side of the planar Bi-circular Restricted Four-Body Problem (PBR4BP) in the synodic frame
% rotating with the two main primaries (P1-P2). The third body (Sun) follows the planar bicircular
% forcing used in the original autogenerated implementation. Non-dimensional units are normalized to
% P1-P2 distance and orbital period.
% NOTE: Sun perturbation parameters were originally generated for the Earth-Moon system.
% -------------------------------------------------------------------------------------------------------------
%% INPUT
% dState       (4,1) double   Planar state [x; y; vx; vy] in synodic frame (non-dim)
% dMassRatio   (1,1) double   Mass ratio m2/(m1+m2) of the two main primaries
% dTime        (1,1) double   Non-dimensional time
% -------------------------------------------------------------------------------------------------------------
%% OUTPUT
% dxdt         (4,1) double   Time derivative of the planar state (non-dim)
% -------------------------------------------------------------------------------------------------------------
%% CHANGELOG
% 20-10-2022    Symbolic Math Toolbox   Auto-generated version.
% 28-03-2026    Claude Code             Manual rewrite with readable variables, documented constants.
% -------------------------------------------------------------------------------------------------------------
%% DEPENDENCIES
% [-]
% -------------------------------------------------------------------------------------------------------------

% Sun perturbation parameters (Earth-Moon system, non-dimensional)
% dSunAngRate: angular rate of Sun in synodic frame [non-dim rad/non-dim time]
% dSunDist: Sun distance from barycenter in non-dim units (normalized to P1-P2 distance)
% dSunGravParam: Sun gravitational parameter in non-dim units = m_Sun / (m1 + m2)
dSunAngRate   = 9.25195985e-1;     % ~0.925 non-dim angular rate
dSunDist      = 3.88811143e+2;     % ~389 P1-P2 distances
dSunGravParam = 3.289005410e+5;    % Non-dim Sun mass parameter

dPosX = dState(1);
dPosY = dState(2);
dVelX = dState(3);
dVelY = dState(4);

dGravP1 = 1 - dMassRatio;
dGravP2 = dMassRatio;

% Relative positions to P1 and P2
dRelX_P1 = dPosX + dMassRatio;
dRelX_P2 = dPosX - (1 - dMassRatio);

% Distances to P1 and P2 (squared)
dDistP1_sq = dRelX_P1^2 + dPosY^2;
dDistP2_sq = dRelX_P2^2 + dPosY^2;
dInvDistP1 = 1.0 / sqrt(dDistP1_sq);
dInvDistP2 = 1.0 / sqrt(dDistP2_sq);
dInvDistP1_3 = dInvDistP1 / dDistP1_sq;
dInvDistP2_3 = dInvDistP2 / dDistP2_sq;
dGravP1OverDistP1_3 = dGravP1 * dInvDistP1_3;
dGravP2OverDistP2_3 = dGravP2 * dInvDistP2_3;

% Sun position in synodic frame.
% ACHTUNG: The legacy autogenerated model uses [R*cos(phase); -R*sin(phase)].
dSunPhase = dSunAngRate * dTime;
dSunPosX = dSunDist * cos(dSunPhase);
dSunPosY = -dSunDist * sin(dSunPhase);

% Position relative to Sun
dRelX_Sun = dPosX - dSunPosX;
dRelY_Sun = dPosY - dSunPosY;
dDistSun_sq = dRelX_Sun^2 + dRelY_Sun^2;
dInvDistSun = 1.0 / sqrt(dDistSun_sq);
dInvDistSun_3 = dInvDistSun / dDistSun_sq;
dSunGravOverDistSun_3 = dSunGravParam * dInvDistSun_3;
dAccIndirectSun = -(dSunGravParam / dSunDist^3) * [dSunPosX; dSunPosY];

% Accelerations: CR3BP terms + Sun gravitational perturbation + indirect term
dAccX = dPosX + 2*dVelY ...
    - dGravP1OverDistP1_3 * dRelX_P1 ...   % P1 gravity
    - dGravP2OverDistP2_3 * dRelX_P2 ...   % P2 gravity
    - dSunGravOverDistSun_3 * dRelX_Sun ...  % Sun direct
    + dAccIndirectSun(1);                    % Sun indirect

dAccY = dPosY - 2*dVelX ...
    - dGravP1OverDistP1_3 * dPosY ...
    - dGravP2OverDistP2_3 * dPosY ...
    - dSunGravOverDistSun_3 * dRelY_Sun ...
    + dAccIndirectSun(2);

dxdt = [dVelX; dVelY; dAccX; dAccY];

end
