function RHS = RHS_CR3BP_planar(x)
%RHS_CR3BP_planar
%    RHS = RHS_CR3BP_planar(X1,X2,X4,X5)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    09-Oct-2022 18:36:55
x1 = x(1);
x2 = x(2);
x4 = x(3);
x5 = x(4);

t2 = x1.*2.0;
t3 = x2.^2;
t4 = x1+3.0./2.5e+2;
t6 = x1-2.47e+2./2.5e+2;
t5 = t4.^2;
t7 = t6.^2;
t8 = t3+t5;
t9 = t3+t7;
t10 = 1.0./t8.^(3.0./2.0);
t11 = 1.0./t9.^(3.0./2.0);
RHS = [x4;x5;x1+x5.*2.0-t10.*(t2+3.0./1.25e+2).*(2.47e+2./5.0e+2)-t11.*(t2-2.47e+2./1.25e+2).*(3.0./5.0e+2);x2-x4.*2.0-t10.*x2.*(2.47e+2./2.5e+2)-t11.*x2.*(3.0./2.5e+2)];
