name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: run_build_lib
      run: echo "Running in $(pwd) directory..." && echo "Warning this is only a template and must be specialized to work" # && bash build_lib.sh
