classdef testComputeQuadsModelSRP < matlab.unittest.TestCase
    %% DESCRIPTION
    % Unit tests for ComputeQuadsModelSRP.
    % Cross-validates the quadrilateral SRP integration against the analytical spherical-shell model.
    % -------------------------------------------------------------------------------------------------------------

    properties (Constant)
        dSunDir_SCB = [1; 0; 0];
        dqIdentity  = [1; 0; 0; 0];
        dMassSC     = 120.0;
        dRadius     = 1.7;
        dSolarPressure = 4.56e-6;
        dRelTolSphericalShell = 1.2e-2;
        dTorqueTolScale = 1.5e-2;
        ui32NumMuBins = uint32(48);
        ui32NumAzBins = uint32(96);
    end

    methods (Test)

        function testSphericalShellCrossValidation(testCase)
            [dQuadsArea, dQuadNormals_SCB, dQuadPressCentre_SCB] = ...
                testCase.buildSphericalShellQuads(testCase.dRadius, testCase.ui32NumMuBins, testCase.ui32NumAzBins);

            dCoeffCases = [0.0, 0.0; ...
                           1.0, 0.0; ...
                           0.0, 1.0; ...
                           0.35, 0.40];

            for idCase = 1:size(dCoeffCases, 1)
                dDiffuseCoeff = dCoeffCases(idCase, 1);
                dSpecularCoeff = dCoeffCases(idCase, 2);
                dDiffSpecQuadsCoeffs = repmat([dDiffuseCoeff, dSpecularCoeff], numel(dQuadsArea), 1);

                [dAccelQuad_IN, dTorqueQuad_SCB, dCosSunPhaseAngle] = ComputeQuadsModelSRP( ...
                    testCase.dSunDir_SCB, ...
                    testCase.dqIdentity, ...
                    testCase.dMassSC, ...
                    zeros(3, 1), ...
                    testCase.dSolarPressure, ...
                    dQuadsArea, ...
                    dDiffSpecQuadsCoeffs, ...
                    dQuadNormals_SCB, ...
                    dQuadPressCentre_SCB);

                dAccelSphere_IN = testCase.computeSphericalShellAcceleration(dDiffuseCoeff);

                testCase.verifySize(dAccelQuad_IN, [3, 1]);
                testCase.verifySize(dTorqueQuad_SCB, [3, 1]);
                testCase.verifySize(dCosSunPhaseAngle, [numel(dQuadsArea), 1]);
                dRelAccelError = norm(dAccelQuad_IN - dAccelSphere_IN) / norm(dAccelSphere_IN);
                testCase.verifyLessThan(dRelAccelError, testCase.dRelTolSphericalShell, ...
                    sprintf('Quadrilateral SRP model must match the spherical-shell solution for case %d', idCase));
                testCase.verifyLessThan(norm(dAccelQuad_IN(2:3)), 1e-18, ...
                    sprintf('Spherical-shell acceleration must remain aligned with the Sun line for case %d', idCase));

                dReferenceTorque = testCase.dSolarPressure * pi * testCase.dRadius^3;
                testCase.verifyLessThan(norm(dTorqueQuad_SCB), testCase.dTorqueTolScale * dReferenceTorque, ...
                    sprintf('Net torque must vanish for a centered spherical shell (case %d)', idCase));
            end
        end

        function testDenseSphericalShellManyQuadsImprovesAnalyticalAgreement(testCase)
            dDiffuseCoeff = 0.35;
            dSpecularCoeff = 0.40;

            [dCoarseArea, dCoarseNormals_SCB, dCoarsePressCentre_SCB] = ...
                testCase.buildSphericalShellQuads(testCase.dRadius, uint32(12), uint32(24));
            [dDenseArea, dDenseNormals_SCB, dDensePressCentre_SCB] = ...
                testCase.buildSphericalShellQuads(testCase.dRadius, uint32(64), uint32(128));

            dCoarseAccel_IN = ComputeQuadsModelSRP( ...
                testCase.dSunDir_SCB, ...
                testCase.dqIdentity, ...
                testCase.dMassSC, ...
                zeros(3, 1), ...
                testCase.dSolarPressure, ...
                dCoarseArea, ...
                repmat([dDiffuseCoeff, dSpecularCoeff], numel(dCoarseArea), 1), ...
                dCoarseNormals_SCB, ...
                dCoarsePressCentre_SCB);

            dDenseAccel_IN = ComputeQuadsModelSRP( ...
                testCase.dSunDir_SCB, ...
                testCase.dqIdentity, ...
                testCase.dMassSC, ...
                zeros(3, 1), ...
                testCase.dSolarPressure, ...
                dDenseArea, ...
                repmat([dDiffuseCoeff, dSpecularCoeff], numel(dDenseArea), 1), ...
                dDenseNormals_SCB, ...
                dDensePressCentre_SCB);

            dAccelSphere_IN = testCase.computeSphericalShellAcceleration(dDiffuseCoeff);
            dCoarseRelError = norm(dCoarseAccel_IN - dAccelSphere_IN) / norm(dAccelSphere_IN);
            dDenseRelError = norm(dDenseAccel_IN - dAccelSphere_IN) / norm(dAccelSphere_IN);

            testCase.verifyGreaterThan(numel(dDenseArea), 20 * numel(dCoarseArea));
            testCase.verifyLessThan(dDenseRelError, dCoarseRelError);
            testCase.verifyLessThan(dDenseRelError, 4e-3);
        end

        function testObjPreprocessorBuildsMultiPanelSRPData(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            charObjPath = fullfile(string(fixture.Folder), "cube_spacecraft.obj");
            [ui32Faces, dVerts] = testCase.buildCubeMesh();
            testCase.writeObjFile(charObjPath, ui32Faces, dVerts);

            dDiffuseCoeff = 0.25;
            dSpecularCoeff = 0.15;
            [strSRPpanelData, objShapeModel] = BuildQuadsModelSRPDataFromObj(charObjPath, ...
                dDiffuseCoeff=dDiffuseCoeff, dSpecularCoeff=dSpecularCoeff);

            testCase.verifyTrue(objShapeModel.hasData());
            testCase.verifyEqual(strSRPpanelData.ui32NumPanels, uint32(12));
            testCase.verifyEqual(numel(strSRPpanelData.dSCquadsArea), 12);
            testCase.verifyEqual(sum(strSRPpanelData.dSCquadsArea), 24.0, 'AbsTol', 1e-14);
            testCase.verifyEqual(strSRPpanelData.dDiffSpecQuadsCoeffs, ...
                repmat([dDiffuseCoeff, dSpecularCoeff], 12, 1), 'AbsTol', 0.0);
            testCase.verifyEqual(vecnorm(strSRPpanelData.dQuadsNormals_SCB, 2, 1), ...
                ones(1, 12), 'AbsTol', 1e-14);

            dOutwardCheck = sum(strSRPpanelData.dQuadsNormals_SCB .* strSRPpanelData.dQuadsPressCentre_SCB, 1);
            testCase.verifyGreaterThan(dOutwardCheck, zeros(1, 12));

            [dAccelCube_IN, dTorqueCube_SCB, dCosSunPhaseAngle] = ComputeQuadsModelSRP( ...
                testCase.dSunDir_SCB, ...
                testCase.dqIdentity, ...
                testCase.dMassSC, ...
                zeros(3, 1), ...
                testCase.dSolarPressure, ...
                strSRPpanelData.dSCquadsArea, ...
                strSRPpanelData.dDiffSpecQuadsCoeffs, ...
                strSRPpanelData.dQuadsNormals_SCB, ...
                strSRPpanelData.dQuadsPressCentre_SCB);

            dExpectedForceCoeff = 1 + 2 * dDiffuseCoeff / 3 + dSpecularCoeff;
            dExpectedAccel_IN = -testCase.dSolarPressure * 4.0 * dExpectedForceCoeff / ...
                testCase.dMassSC * testCase.dSunDir_SCB;

            testCase.verifyEqual(sum(dCosSunPhaseAngle > 0), 2);
            testCase.verifyEqual(dAccelCube_IN, dExpectedAccel_IN, 'RelTol', 1e-14, 'AbsTol', 1e-18);
            testCase.verifyEqual(dTorqueCube_SCB, zeros(3, 1), 'AbsTol', 1e-18);
        end

        function testSinglePanelAnalyticalForceAndTorque(testCase)
            dArea = 2.0;
            dDiffuseCoeff = 0.3;
            dSpecularCoeff = 0.2;
            dNormal_SCB = [1; 0; 0];
            dPressCentre_SCB = [0; 0.5; 0];
            dCoMpos_SCB = zeros(3, 1);

            [dAccelQuad_IN, dTorqueQuad_SCB, dCosSunPhaseAngle] = ComputeQuadsModelSRP( ...
                testCase.dSunDir_SCB, ...
                testCase.dqIdentity, ...
                testCase.dMassSC, ...
                dCoMpos_SCB, ...
                testCase.dSolarPressure, ...
                dArea, ...
                [dDiffuseCoeff, dSpecularCoeff], ...
                dNormal_SCB, ...
                dPressCentre_SCB);

            dExpectedForce_SCB = -testCase.dSolarPressure * dArea * ...
                (2 * (dDiffuseCoeff / 3 + dSpecularCoeff) * dNormal_SCB + ...
                (1 - dSpecularCoeff) * testCase.dSunDir_SCB);
            dExpectedAccel_IN = dExpectedForce_SCB / testCase.dMassSC;
            dExpectedTorque_SCB = cross(dPressCentre_SCB - dCoMpos_SCB, dExpectedForce_SCB);

            testCase.verifyEqual(dCosSunPhaseAngle, 1.0, 'AbsTol', 1e-15);
            testCase.verifyEqual(dAccelQuad_IN, dExpectedAccel_IN, 'RelTol', 1e-14, 'AbsTol', 1e-18);
            testCase.verifyEqual(dTorqueQuad_SCB, dExpectedTorque_SCB, 'RelTol', 1e-14, 'AbsTol', 1e-18);
        end

        function testBacksidePanelProducesZeroForceAndTorque(testCase)
            [dAccelQuad_IN, dTorqueQuad_SCB, dCosSunPhaseAngle] = ComputeQuadsModelSRP( ...
                testCase.dSunDir_SCB, ...
                testCase.dqIdentity, ...
                testCase.dMassSC, ...
                zeros(3, 1), ...
                testCase.dSolarPressure, ...
                1.0, ...
                [0.3, 0.2], ...
                [-1; 0; 0], ...
                [0; 1; 0]);

            testCase.verifyEqual(dCosSunPhaseAngle, -1.0, 'AbsTol', 1e-15);
            testCase.verifyEqual(dAccelQuad_IN, zeros(3, 1), 'AbsTol', 0.0);
            testCase.verifyEqual(dTorqueQuad_SCB, zeros(3, 1), 'AbsTol', 0.0);
        end

        function testTorqueOutputCanBeOmitted(testCase)
            dAccelWithTorque_IN = ComputeQuadsModelSRP( ...
                testCase.dSunDir_SCB, ...
                testCase.dqIdentity, ...
                testCase.dMassSC, ...
                zeros(3, 1), ...
                testCase.dSolarPressure, ...
                1.0, ...
                [0.2, 0.1], ...
                [1; 0; 0], ...
                [0; 1; 0]);

            [dAccelFull_IN, ~] = ComputeQuadsModelSRP( ...
                testCase.dSunDir_SCB, ...
                testCase.dqIdentity, ...
                testCase.dMassSC, ...
                zeros(3, 1), ...
                testCase.dSolarPressure, ...
                1.0, ...
                [0.2, 0.1], ...
                [1; 0; 0], ...
                [0; 1; 0]);

            testCase.verifyEqual(dAccelWithTorque_IN, dAccelFull_IN, 'AbsTol', 0.0);
        end

    end

    methods (Access = private)

        function dAccelSphere_IN = computeSphericalShellAcceleration(testCase, dDiffuseCoeff)
            dProjectedArea = pi * testCase.dRadius^2;
            dSphereCoeff = 1 + (4 / 9) * dDiffuseCoeff;
            dAccelSphere_IN = -(testCase.dSolarPressure * dProjectedArea * dSphereCoeff / testCase.dMassSC) * testCase.dSunDir_SCB;
        end

        function [dQuadsArea, dQuadNormals_SCB, dQuadPressCentre_SCB] = buildSphericalShellQuads(~, dRadius, ui32NumMuBins, ui32NumAzBins)
            dMuEdges = linspace(-1, 1, double(ui32NumMuBins) + 1);
            dAzEdges = linspace(0, 2 * pi, double(ui32NumAzBins) + 1);

            nQuads = double(ui32NumMuBins * ui32NumAzBins);
            dQuadsArea = zeros(nQuads, 1);
            dQuadNormals_SCB = zeros(3, nQuads);
            dQuadPressCentre_SCB = zeros(3, nQuads);

            dDeltaAz = dAzEdges(2) - dAzEdges(1);
            idQ = 1;
            for idMu = 1:double(ui32NumMuBins)
                dMuCenter = 0.5 * (dMuEdges(idMu) + dMuEdges(idMu + 1));
                dSinEl = sqrt(max(0, 1 - dMuCenter^2));

                for idAz = 1:double(ui32NumAzBins)
                    dAzCenter = 0.5 * (dAzEdges(idAz) + dAzEdges(idAz + 1));

                    dQuadNormals_SCB(:, idQ) = [dSinEl * cos(dAzCenter); ...
                                                dSinEl * sin(dAzCenter); ...
                                                dMuCenter];
                    dQuadPressCentre_SCB(:, idQ) = dRadius * dQuadNormals_SCB(:, idQ);
                    dQuadsArea(idQ) = dRadius^2 * dDeltaAz * (dMuEdges(idMu + 1) - dMuEdges(idMu));
                    idQ = idQ + 1;
                end
            end
        end

        function [ui32Faces, dVerts] = buildCubeMesh(~)
            dVerts = [-1 -1 -1; ...
                       1 -1 -1; ...
                       1  1 -1; ...
                      -1  1 -1; ...
                      -1 -1  1; ...
                       1 -1  1; ...
                       1  1  1; ...
                      -1  1  1];

            ui32Faces = uint32([1 4 3; ...
                                1 3 2; ...
                                5 6 7; ...
                                5 7 8; ...
                                2 7 6; ...
                                2 3 7; ...
                                1 5 8; ...
                                1 8 4; ...
                                4 7 3; ...
                                4 8 7; ...
                                1 2 6; ...
                                1 6 5]);
        end

        function writeObjFile(~, charObjPath, ui32Faces, dVerts)
            fid = fopen(char(charObjPath), "w");
            assert(fid ~= -1, "testComputeQuadsModelSRP:FileOpenFailed", ...
                "Failed to create temporary OBJ file: %s", char(charObjPath));
            cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>

            for idVert = 1:size(dVerts, 1)
                fprintf(fid, "v %.16g %.16g %.16g\n", dVerts(idVert, 1), dVerts(idVert, 2), dVerts(idVert, 3));
            end

            for idFace = 1:size(ui32Faces, 1)
                fprintf(fid, "f %u %u %u\n", ui32Faces(idFace, 1), ui32Faces(idFace, 2), ui32Faces(idFace, 3));
            end
        end

    end
end
