classdef testGaussMarkovAccelSeq < matlab.unittest.TestCase
    methods (Test)
        function testGeneratedSequenceIsRepeatableForFixedSeed(testCase)
            strProfileA = GenerateGaussMarkovAccelSeq([10.0, 70.0], ...
                                                       [1.0e-9; 2.0e-9; 3.0e-9], ...
                                                       [100.0; 120.0; 140.0], ...
                                                       10.0, ...
                                                       uint32(42));
            strProfileB = GenerateGaussMarkovAccelSeq([10.0, 70.0], ...
                                                       [1.0e-9; 2.0e-9; 3.0e-9], ...
                                                       [100.0; 120.0; 140.0], ...
                                                       10.0, ...
                                                       uint32(42));

            testCase.verifyEqual(strProfileA.dTimeGrid, 10.0:10.0:70.0, 'AbsTol', 0.0);
            testCase.verifyEqual(strProfileA.dAccelGrid, strProfileB.dAccelGrid, 'AbsTol', 0.0);
            testCase.verifyEqual(strProfileA.dStandardNormalInnovation, ...
                                 strProfileB.dStandardNormalInnovation, ...
                                 'AbsTol', 0.0);
            testCase.verifyEqual(strProfileA.charFrame, 'IN');
            testCase.verifyEqual(strProfileA.charSequenceModel, 'statistics_preserving');
        end

        function testEvalMatchesGridAndUsesSegmentInnovationBetweenGridPoints(testCase)
            strProfile = GenerateGaussMarkovAccelSeq([0.0, 20.0], ...
                                                     [1.0; 2.0; 3.0], ...
                                                     [40.0; 50.0; 60.0], ...
                                                     10.0, ...
                                                     uint32(7), ...
                                                     'dInitialAccel', [0.1; -0.2; 0.3], ...
                                                     'bSampleInitialAccel', false);

            testCase.verifyEqual(EvalGaussMarkovAccel(0.0, strProfile), ...
                                 strProfile.dAccelGrid(:,1), ...
                                 'AbsTol', 0.0);
            testCase.verifyEqual(EvalGaussMarkovAccel(10.0, strProfile), ...
                                 strProfile.dAccelGrid(:,2), ...
                                 'AbsTol', 1.0e-14);
            testCase.verifyEqual(EvalGaussMarkovAccel(20.0, strProfile), ...
                                 strProfile.dAccelGrid(:,3), ...
                                 'AbsTol', 0.0);

            dElapsed = 5.0;
            dPhi = exp(-dElapsed ./ strProfile.dTimeConst);
            dExpected = strProfile.dMeanAccel + ...
                dPhi .* (strProfile.dAccelGrid(:,1) - strProfile.dMeanAccel) + ...
                strProfile.dSigmaAccel .* sqrt(1.0 - dPhi.^2) .* ...
                strProfile.dStandardNormalInnovation(:,1);

            testCase.verifyEqual(EvalGaussMarkovAccel(dElapsed, strProfile), ...
                                 dExpected, ...
                                 'AbsTol', 1.0e-14);
        end

        function testMaxFidelityRhsAddsStochasticAccelerationWhenEnabled(testCase)
            dxState = [4; 0; 0; 0; 0.2; 0];
            strDynParams = testCase.buildCentralDynParams();
            strDynParams.strStochasticAccelData = GenerateGaussMarkovAccelSeq([0.0, 20.0], ...
                                                                              [0.0; 0.0; 0.0], ...
                                                                              [100.0; 100.0; 100.0], ...
                                                                              10.0, ...
                                                                              uint32(1), ...
                                                                              'dInitialAccel', [1.0e-8; -2.0e-8; 3.0e-8], ...
                                                                              'bSampleInitialAccel', false);
            strModelConfigFlagsOff = struct('bIncludeThirdBodies', false, ...
                                            'bIncludeSRP', false, ...
                                            'bIncludeSphericalHarmonics', false, ...
                                            'bIncludeStochasticAcceleration', false);
            strModelConfigFlagsOn = strModelConfigFlagsOff;
            strModelConfigFlagsOn.bIncludeStochasticAcceleration = true;

            dxOff = evalRHS_InertialDynMaxFidelity(0.0, dxState, strDynParams, strModelConfigFlagsOff);
            [dxOn, strAccelInfo] = evalRHS_InertialDynMaxFidelity(0.0, dxState, strDynParams, strModelConfigFlagsOn);

            testCase.verifyEqual(dxOn(1:3), dxOff(1:3), 'AbsTol', 0.0);
            testCase.verifyEqual(dxOn(4:6) - dxOff(4:6), ...
                                 [1.0e-8; -2.0e-8; 3.0e-8], ...
                                 'AbsTol', 1.0e-16);
            testCase.verifyEqual(strAccelInfo.dAccStochastic_IN, ...
                                 [1.0e-8; -2.0e-8; 3.0e-8], ...
                                 'AbsTol', 0.0);
        end
    end

    methods (Access = private)
        function strDynParams = buildCentralDynParams(~)
            strDynParams = struct();
            strDynParams.strMainData = struct('dGM', 1.0, ...
                                              'dRefRadius', 1.0, ...
                                              'dSHcoeff', [], ...
                                              'ui16MaxSHdegree', uint16(0));
            strDynParams.strSRPdata = struct('dP_SRP0', 0.0, ...
                                             'dP_SRP', 0.0, ...
                                             'dReferenceDistance', 1.0, ...
                                             'bRecomputePressureFromDistance', true);
            strDynParams.strSCdata = struct('dReflCoeff', 1.0, ...
                                            'dSCmass', 1.0, ...
                                            'dA_SRP', 0.0);
        end
    end
end
